### ISSUE TITLE
Check User/Date Created/Modified Interfaces

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1057]
There have been reports that these are not working properly.

**Comment by rijkvanzanten** [comment]
@WellingGuzman 

⚠️  datetime_updated only saves datetime_created, doesn't update
⚠️  user_updated doesn't save anything

Other than that, this seems to work as expected.

The only annoying thing @benhaynes, you need to use the "save-to-from UTC" option in the datetime interface in order for it to display the time converted from UTC.

We need to consider creating a separate datetime interface for UTC maybe instead of having it as an option 🤔 Or maybe consider making a read-only one that's just used for system date times (activity / updated / created)

**Comment by benhaynes** [comment]
All four of these are working for me... @rijkvanzanten 

I'll create new interfaces for them now.

**Comment by benhaynes** [comment]
We have dedicated interfaces and some new Docs to explain how to set them up.
