### ISSUE TITLE
Must hard refresh after creating M2M

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1072]
If you create a M2M field and then try to use it you get an error (I didn't copy it) and it doesn't work. But if you hard-refresh the App it works as expected. We should fix this or have the App hard refresh on it's own... 🤢

**Comment by shealavington** [comment]
I was about to add this as a bug myself, as I came across this issue, I was getting an error along the lines of `'collection_one' doesn't exist` in my console, perhaps when trying to `ADD NEW` or `SELECT EXISTING`, it thinks it's on a different collection, and the hard-refresh gives the frontend the correct collection?

**Comment by samvasko** [comment]
There are couple more issues that are related to this.
1. When creating a new item from related item the table does not get populated with values that are generated by the server

<img width="661" alt="screen shot 2019-02-17 at 17 55 48" src="https://user-images.githubusercontent.com/2674600/52917053-ce7df300-32de-11e9-8c7a-0c8dd60b7c61.png">

2. After adding an item selecting new item from exiting does not work due to lack of said properties.

**Comment by benhaynes** [comment]
Hey @samvasko — this seems like a different issue. This one is related to the interface acting odd _directly after being created_. You're talking about the interface in general, I think. Mind opening a new ticket so this doesn't get lost in the shuffle? (unless I'm mistaken)

**Comment by emd2013** [comment]
Can confirm i am getting this issue.
