### ISSUE TITLE
Dropdown template - issue with popup template

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1075]
# Question

I define a dropdown template : **{{id}} - {{label}}**

## Actual Behavior
This dropdown is respected in main form (yellow) but not in popup (see screenshot)

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/34483024/48063728-3728e000-e1c6-11e8-8ba4-3f9a30fa56cd.png)

Am I doing something wrong ?

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus App: 7.0.0

**Comment by benhaynes** [comment]
I _think_ this is intended behavior, but we might want to use the template until we have a way to update the fields. The reason that the tabular view is better is because it is adjustable and can show more than text... eg: image thumbnails.

I think the **Listing View Preferences** are meant to adjust this view, but we need to check with @rijkvanzanten . Also, we need a better interface for updating that option... or at least Docs on how to create them.

**Comment by benhaynes** [comment]
These two seem related: https://github.com/directus/app/issues/1073#event-2070551884

@rijkvanzanten can we discuss how these interface setup could be simplified so it's easier to create?

**Comment by rijkvanzanten** [comment]
Like @benhaynes mentioned, this is intended behavior. We can consider adding a dropdown-only m2o interface or add an option that sets the threshold for when it switches from a dropdown to the full select modal.

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/issues/1321
