### ISSUE TITLE
Dropdown - Choices not showing

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1078]
# Bug Report

## Steps to Reproduce

In an existing table, I set one of my field (which has a default value to 'IN STOCK') to Dropdown interface and set, in options, the choices as follow :
![image](https://user-images.githubusercontent.com/34483024/48073550-47998480-e1df-11e8-833e-ede9bfe164cb.png)

When I want to edit an item : nothing appeared 
![image](https://user-images.githubusercontent.com/34483024/48073606-64ce5300-e1df-11e8-89d5-4a9f4c1d83fd.png)

## Expected Behavior
I hope to have a dropdown with the choices I defined

## Actual Behavior
No interface.

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus App: 7.0.0

**Comment by carolin-skiply** [comment]
I edited again my field and it appear that the choices weren't saved
![image](https://user-images.githubusercontent.com/34483024/48074389-191ca900-e1e1-11e8-8d9c-368ceccaae86.png)

So enter them again but same issue, the choice weren't saved

**Comment by rijkvanzanten** [comment]
Hey @carolin-skiply, this seems to be working fine on my end. Could you try it in the latest version of the app? (7.0.5)

**Comment by rijkvanzanten** [comment]
Ohh scratch that, I see what's up. The JSON for the options you're providing is invalid. JSON uses double quotes `"` instead of single quotes `'`.

It's not a bug in the interface per se, as this is not supposed to work.

However, I'll add a check in the dropdown interface that will replace the interface with a warning message if the provided options are invalid in any way.
