### ISSUE TITLE
Sorting values on the display value and not the database value

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1107]
# Feature Request
I've a field (in hexadecimal) that I have to parse to extract and convert to get the actual value. I created an interface which process the data as desired and display the actual value. 
I want to sort the actual value (displaied thanks to my interface) and not the database value.

## What problem does this feature solve?
Sorting the data on the value in the database and not the actual value.

## How do you think this should be implemented?
Use a filter in JS (using the display value) and not in MYSQL.

**Comment by benhaynes** [comment]
I'd like to get the opinion of @rijkvanzanten and @WellingGuzman on this. I don't really thing it's possible for the following reasons:

1. This would not work when there is more than one page of data since the client-side would need to have all values to sort properly
2. Sorting on client-side (App) means that the API would return things in a different order since the API doesn't consider interface values.
3. We could have an App option that the data is sorted client-side if all items in the collection fit on one page... but I don't know how useful this would be.

This ticket was marked as `stale`, if neither Rijk nor Welling think this is a good idea or within our [80/20](https://docs.directus.io/getting-started/contributing.html#_80-20-rule) then I will close it.

**Comment by rijkvanzanten** [comment]
@benhaynes you're right. It would only work if the client already has all the items in a collection. That won't be possible for a lot of collections, as we try not to load more than 200 items at a time. The API doesn't now how a value will be displayed, so it can't really sort by that either.

No 3 is true, but I agree that I don't see the usefulness. It will also introduce way more complexity as now sorting will work differently based on the context of a collection.
