### ISSUE TITLE
French locale not available

### ISSUE THREAD

**Issue by sebj54** [directus/app#1115]
# Bug Report

## Steps to Reproduce

1. Go to "My profile"
2. Click on the select menu "Locale"

## Expected Behavior

French locale should be available.
*Maybe I'm wrong but I see the `fr-FR` file in `src/lang/locales/` in the repository and there are serveral `lang-fr-FR-*` files in the `public/admin/js` folder in my install directory.*

## Actual Behavior

French locale isn't available.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/5880435/48491069-fe70b280-e826-11e8-8337-7268de31238f.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Firefox latest
- Directus App: 7.0.6
- Directus API: latest?
- Install Method: Cloned master branch of bundled Directus

**Comment by rijkvanzanten** [comment]
Right now, this option uses a regular dropdown interface which options are configured in the DB. Adding new languages in the system right now relies on us updating the options for that dropdown in everyone's database for every new language. Very inconvenient! I'll create a new language interface that pulls it's values from the local application instance instead of using the DB options for it. Expect this in the next release on Friday as we're adding new languages almost on a weekly basis.

Thanks for pointing this out @sebj54!

**Comment by sebj54** [comment]
Cool, happy to be helpful 😃 

I tested a few weeks ago Directus 6 and I saw it was available in French (prerequisite for my project), so I was surprised when I saw this bug!

From what I remember, there were also missing translations in French, is it still the case? Can I check that by manually adding the 'fr-FR' locale in the DB? If yes, how?

If I have time before Friday, I may submit a PR with fixes if there are missing translations :)

**Comment by rijkvanzanten** [comment]
If you change the `en-US` to `fr-FR` in the `locale` column of the  `directus_users` table in the database, the app will display in French. Based on the lengths of the English language file vs the French one, there are about 20 keys missing.

**Comment by sebj54** [comment]
Great! Thanks, I'll make a PR before Friday so 😃

**Comment by rijkvanzanten** [comment]
Also, feel free to adjust any other translations which feel odd or wrong. I'm not a French speaker so I personally have no clue on how solid the translations are at this point 😁

**Comment by sebj54** [comment]
Good advice, I'll review them all! 😄
