### ISSUE TITLE
Multiple WYSIWYG fields throws error

### ISSUE THREAD

**Issue by anonlethal-jerk** [directus/app#1136]
Directus 7.0.8
PHP 7.2.10
MySQL 5.7.23

Hello,

I am trying to add two WYSIWYG fields to a collection, but it is having "trouble processing request"

<img width="346" alt="screen shot 2018-11-17 at 11 08 28" src="https://user-images.githubusercontent.com/25354950/48663174-298f1800-ea5a-11e8-831b-cab1386eecbf.png">

I can delete the original WYSIWYG field and recreate it, but I can't add a second.

**Comment by rijkvanzanten** [comment]
The problem here is that the interfaces don't provide a specific MySQL type (eg TEXT) but instead specify a Directus datatype (eg String) so it's database agnostic. We made the choice to make the `String` Directus type map to a `VARCHAR` in MySQL by default. The WYSIWYG editor then asks for a length of `10000`, so you don't run into space issues in the WYSIWYG.

I'd like to keep the MySQL specific types out of the interfaces, as that's going to be quite hard to maintain over different versions of MySQL and later other SQL database types.

We can change the Directus `String` type to map to `TEXT` instead, but that will have the effect that all string based fields will use `TEXT` by default...

Alternatively, we can change the default length of a WYSIWYG to `65535` (the max allowed size of a VARCHAR in utf8mb4) instead of the `100000`.

Thoughts @benhaynes @anonlethal-jerk?

_I'll update the length to 65535 as a "fix" for now, but it's not necessarily the right "solution"._

**Comment by benhaynes** [comment]
My thoughts:

We should solve this in the ticket I referenced: https://github.com/directus/app/issues/952

Basically using the length to map to a vendor specific datatype. So for our MySQL `string` mapping:

| Recommended Length | MySQL Datatype |
|-----------------------|-------------------|
| x <= 500                         | VARCHAR            |
| 500 < x < 65,535           | TEXT                    |
| 65,535 < x                      | LONGTEXT          |
