### ISSUE TITLE
WYSIWYG field not rendering (404 issues)

### ISSUE THREAD

**Issue by andreekeberg** [directus/app#1142]
# Bug Report

## Steps to Reproduce

1. Clone the latest release of directus from GitHub
2. Setup a collection (in my case named "pages")
3. Add some fields to it (status, title, slug and WYSIWYG)

## Expected Behavior

I'm expecting to see the WYSIWYG field when adding/editing a page.

## Actual Behavior

The WYSIWYG fields seems to render as a standard "textarea" field, and the following errors appear in the console:

load-extension.js:41 GET http://directus.pocket/extensions/core/layouts/tabular/layout.css net::ERR_ABORTED 404 (Not Found)
load-extension.js:41 GET http://directus.pocket/extensions/core/interfaces/slug/display.css net::ERR_ABORTED 404 (Not Found)
load-extension.js:41 GET http://directus.pocket/extensions/core/interfaces/wysiwyg/display.css net::ERR_ABORTED 404 (Not Found)
load-extension.js:41 GET http://directus.pocket/extensions/core/interfaces/text-input/display.css net::ERR_ABORTED 404 (Not Found)

## Other Context & Screenshots

In the URL's above, _directus.pocket_ is the local development domain for my Directus installation.

## Technical Details

- Device: Desktop
- OS: macOS Sierra 10.12.6 (16G1618)
- Browser: Chrome 70.0.3538.77
- Directus App: 7.0.8
- Directus API: 2.0.8
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
> I just realized that the editing buttons appear when selecting text.

The WYSIWYG is a medium-style editor. If you're looking for a more "traditional" WYSIWYG experience, you can try the WYSIWYG Advanced editor. That one has a bunch more features as well.

> the 404 errors persist

The missing .css files is a known issue, but I don't know how to solve it :( Lemme know if you have any thoughts on the following:

The extensions are made up of `.vue` components. These `.vue` files are split up into `.js` and `.css` files so they can be used in the application. However, a few extensions (like the 4 listed above) don't have any styles associated to them! This results in the build chain not generating the `.css` file. The problem here is that the application can't check if the `.css` file exists before trying to load it. So what's happening here is that the application is trying to load both the `.js` and `.css` files, but the `.css` file doesn't exist and thus results in a 404 error.

I have considered building both the `.css` and `.js` into one `.js` file to prevent this from happening, but having the css and js split is pretty nice on `http2` servers and has some pros in terms of caching.

It's too bad I can't have the browser ignore 404 errors for files, as that's outside of reach for the program.

**Comment by andreekeberg** [comment]
Ah, I understand, will try the advanced editor in that case.
Thank you for the suggestion!

Regarding the 404 issues, I recognize that from our internal webpack build system as well, no worries then, as long as it's not an actual problem with the admin app!

**Comment by lingej** [comment]
whats about adding an empty .css to avoid the 404 error?

**Comment by benhaynes** [comment]
That could work — @rijkvanzanten maybe we could do that in 7.0.10 to avoid all of these 404s? Do we want a ticket for that?

**Comment by andreekeberg** [comment]
Speaking of that, could you not leverage a rewrite rule that uses the `!-f` flag to rewrite all requests to `.css` files that does not exist to an empty one, or possibly even easier use a custom `ErrorDocument` rule to send 404 errors in these folders to the empty file? Something like:

`ErrorDocument 404 /empty.css`

**Comment by lingej** [comment]
@andreekeberg please dont do that!

every 404 will serve an empty file and the config will only work on apache.
Also you are not able to use a custom 404 file anymore
