### ISSUE TITLE
Is it possible to hide users directory to users that are not Admin

### ISSUE THREAD

**Issue by carolin-skiply** [directus/app#1155]
# Bug Report
When I log with a user with a Member role (not Admin), I can still access to Users Directory.

## Steps to Reproduce

1. Create a new role : Member
2. Create a new user and affect the role Member to this user
3. Connect with this new user.

## Expected Behavior
At least hide users that have not the same role or hide users directory menu

## Actual Behavior
The user have access to users directory and can see all other users. If we want to give access to our platform to our client, we don't want them to see others clients.

## Technical Details

- Device: Desktop
- OS: Windows
- Browser: Chrome
- Directus App: 7.0.x
- Install Method: cloned `master` branch

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/49254330-44359980-f429-11e8-8ad0-45404be709bb.png)

You can toggle the Directus database view and change the readability for an group to read the user DB or to limit them to only read their profile.

### But be carefull!!
It might be that Directus wont work properly anymore for this group due to limited permissions etc.

**Comment by carolin-skiply** [comment]
Thanks.
