### ISSUE TITLE
Main text input widget

### ISSUE THREAD

**Issue by dur41d** [directus/app#1161]
# Feature Request

I like the text layout in [forestry.io](https://forestry.io/) (static site generator) where the half the page is reserved for the main text and all the other fields are on the left side. I think for blog entry this is really useful as it gives a big screen real estate to the main text where most of the time will be spent. And i think it's a common use case.

## What problem does this feature solve?

Giving more screen real estate to big text input.

## How do you think this should be implemented?

I suggest adding another widget called 'Main Text' and there could be only one per collection. 

## Would you be willing to work on this?

Sure:)

![image](https://user-images.githubusercontent.com/1318592/49330175-26ffe880-f559-11e8-8df5-113783b00c6f.png)

**Comment by rijkvanzanten** [comment]
@benhaynes we should take this into considerations when designing the grid system on the detail page.

**Comment by benhaynes** [comment]
Thanks @dur41d — did you see the "Distraction Free" mode that we included on the WYSIWYG editor? It transforms the editor into a fullscreen interface. Does that solve this issue or are there improvements we could make to that option to better resolve this?

We can also look into a "side-by-side" editor layout (so other fields are visible at the same time) but as Rijk said, that's a more structural update.

I'd love to hear your thoughts on this!

**Comment by rijkvanzanten** [comment]
As for the original idea of 

> I suggest adding another widget called 'Main Text' and there could be only one per collection.

I think this is too use case specific for Directus to implement as a rule for everybody. It makes sense for blog style websites, but that's not the only thing people use Directus for.

**Comment by dur41d** [comment]
@rijkvanzanten I think blog like sites are very common. I think it helps to think that your #1 competitor is wordpress.

**Comment by dur41d** [comment]
@benhaynes Yes I've seen the 'Distraction Free' mode in WYSIWYG and it's good. However the WYSIWYG is very limited compared to the Advanced WYSIWYG. If this mode is available in the advanced editor then that would be Ok but not idea. Having a side-by-side editing experience is more user friendly as the user does not have to switch back and forth between editing modes. 

To give you perspective, the regular user add/updates/modifies about 50 articles a day and it quickly becomes time consuming to scroll down ...enable distraction free mode ...edit.. close.. save..etc.

**Comment by benhaynes** [comment]
Makes sense. Some of these issues could be resolved with the current method:

1. We could have full screen options _not_ go over the header, so you don't need the extra steps to save
2. You can order fields so that WYSIWYG is at the top (avoiding the scroll step)
3. Alternatively, you could adjust the sizing of the WYSIWYG to be wider/taller and be the first field
4. All long-form or larger interfaces (eg: maps) could utilize the full-screen mode. That way the Advanced WYSIWYG would also have it built in.

I'm not saying that your direction isn't a good one, but it does change the form layout in a major way by creating an exception for a single type of field. Also, it is very viewport/device specific as this wouldn't work on smaller screens. Lastly, there's the issue of how this get's "designed" in the field layout grid: https://github.com/directus/app/issues/773

Let's keep discussing, hopefully we can find a good balance. I agree that long-form writing is extremely important to content entry authoring, so it's potentially worth special features like this.

One final point is that I certainly don't consider WordPress to be our largest (or even a significant) competitor. If you want a quick blog-style website with premade design templates to choose from... then WordPress might be a better option. I've always thought of the Directus Market as: _everyone who has outgrown the limitations of traditional CMS like WordPress_.

**Comment by dur41d** [comment]
Good points. I have comment about the viewport/device. I think it's safe that to consider that the admin interface will be mostly used in a desktop,laptop, or tablet. It's hard for me to imagine someone using his phone to add edit his website.. possible but unlikely.

The other comment about Wordpress. I think 'competitor' is inaccurate term. However, I think that you (or any other CMS) will always be compared to WP and its feature set.
