### ISSUE TITLE
Search input for interfaces during field setup

### ISSUE THREAD

**Issue by rw3iss** [directus/app#1178]
# Feature Request

## What problem does this feature solve?
Finding a specific field type more easily when adding or editing collection fields.

## How do you think this should be implemented?
A search box or bar at the top of the field selection modal, maybe stays sticky, hides when scrolling down, shown when scrolling back upward kind of thing. It should filter the items in each type/section as you type, perhaps auto-expanding a section if it has matches... otherwise just showing a single section with all results together.

## Would you be willing to work on this?
Probably

**Comment by benhaynes** [comment]
I love this idea (it was in the original design but didn't make it in due to time). I think it would be great if you could navigate this pane with the keyboard only... and that led to me thinking that a listing might be better than a card view.

We could do something like this, with the search input filtering down and accessible with the arrow keys. And yes, the search input could sticky to the top (I don't think we even need to hide it on scroll down). Ideally users can search for any text (interface, category, and keywords). The selected interface would always go to the top of the list.

Thoughts @rw3iss and @rijkvanzanten ?

![directus 7 collections fields create field](https://user-images.githubusercontent.com/522079/49761463-2ff96400-fc95-11e8-8fff-7b81ceaa69d0.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
