### ISSUE TITLE
Add repeater field

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1205]
# Repeater

Allow the ability for a field or collection of fields to be repeatable inside an Item. 

For instance allow for an image field to be repeated multiple times in one Item. A single item could have 1,5, 10, 25 etc.. images based on the needs of the specific item. This would be especially useful in blog style items or product items that may have a slider with a undefined number of images. 

## How it Works

A repeator field would consists of a single child or multiple children fields. In an item the repeater field would allow you to create virtually an endless repetition of that collection of fields. i.e. you could add 1 image to the item or 25 images to the item.

This would be a one-to-many relational interface. I think we can re-use parts of the translation interface.

**Comment by Log1x** [comment]
Eagerly awaiting the repeater field. This is a must-have for a majority of sites I build.

**Comment by Log1x** [comment]
Something similar to the relational field seems fitting. 

The only extensively used repeater concept I'm familiar with is how they are implemented in [ACF Pro](https://www.advancedcustomfields.com/resources/repeater/).

**Comment by benhaynes** [comment]
As soon as we have the UUID (with collection prefix) primary key option in the API, then we can build this repeater interface. 

Not sure if the API relations need to be updated to return data based on this new UUID key though. 

@wellingguzman thoughts?

**Comment by WellingGuzman** [comment]
I have no thoughts, I still don't understand how this UUID with collection prefixed will work or if the ID will be collection name + an UUID.

**Comment by benhaynes** [comment]
It would work the same as "M2M" does now — but the junction table would store the new PK type. I think we can avoid calling it a UUID... it's a new Directus specific PK type that concats the collection name and `id`:

`articles-123`

That way we can explode it to see the collection and PK/ID. With a UUID we would have to search ALL tables to find where it came from:

`e1ded180-e6f3-46dc-8c53-9272ba6328a8`

The only difference with this "repeater" M2M field is that items can come from multiple collections... so this new PK type would solve that. Does that make more sense @WellingGuzman ?

**Comment by rijkvanzanten** [comment]
@benhaynes You're thinking of the m2mm / matrix / page builder stuff

Repeater fields are way simpler, as they are technically a one to many relationship with a different interface.

**Comment by rijkvanzanten** [comment]
Eg a repeater field repeats the same fields over and over again, those fields would come from a different collection in this case.

**Comment by WellingGuzman** [comment]
> I think we can avoid calling it a UUID... it's a new Directus specific PK type that concats the collection name and `id`:

Makes more sense now as calling UUID was confusing me. Also it will be hard to tell apart where the collection name ends and where the item id begins.

**Comment by benhaynes** [comment]
Ahh, thanks @rijkvanzanten! I will stop adding M2X info stuff here then 😬 

@WellingGuzman — awesome! Glad the M2X makes more sense. We can continue that conversation over here: https://github.com/directus/api/issues/8

**Comment by rubenmeines** [comment]
I am using the repeater field non relational, it is for reusing elements in the same style but with unique content. 

I am making a recipe website and I'm using repeaters in the ingredients section, with different quantity of those ingredients and a more simple repeater is the steps to make the actual recipe.

checkout https://tostibanaan.nl and click on a recipe to see the actual data. I'm currently using the wordpress api with ACF pro plugin.

**Comment by rijkvanzanten** [comment]
@rubenmeines how would you prefer to save this to the DB if it's non relational? 

CSV? JSON? 

_PS toffe site! Ga binnenkort wat recepten proberen 😊_

**Comment by rubenmeines** [comment]
@rijkvanzanten I'm not sure if I said it correctly using the word 'relational', because it is relational to the "recipe" in this case. (Just so you know, I am not a backend/database expert). 

This is the JSON that I am using right now for a recipe (not generated by directus):
http://tostibanaan.com/wp-json/wp/v2/recept?427&fields=id,slug,title.rendered,acf,temas
This is working for me and I would like to be able to recreate this in directus. 

It is a field that makes it possible to repeat a specific type of field or repeat a group of fields. Check the link to the json and search for the 'ingredients' and 'recipe_instructions' object.

I hope this makes sense!

PS: @rijkvanzanten haha thanks!

**Comment by rijkvanzanten** [comment]
This structure is in fact relational 🙂 In this case, you'd have a `recipe_instructions` collection, with a one-to-many from `recipes` to `recipe_instructions`. This one to many interface would have to render the values inline to make it a "repeater" field

**Comment by benhaynes** [comment]
So, this actually should be _fairly_ easy to build since it's essentially just an "inline O2M". Here's a quick example of what this could look like — and since we're full-steam ahead on v7.1, this mock uses the new design system.

Also, it should be noted that this interface uses an offset container so that it's field children don't break the standard form grid. However this means that we couldn't allow nested repeaters. But that's just bad UX anyway — and you could use nested O2Ms, which are almost the same thing!

![screen shot 2019-01-28 at 8 44 25 pm](https://user-images.githubusercontent.com/522079/51878475-cb29c400-233d-11e9-81e9-b41f845a2cfe.png)

I'd love to get some initial feedback on this rough design. Once we're happy with it we'll get it built!

**Comment by rubenmeines** [comment]
> This structure is in fact relational 🙂 In this case, you'd have a `recipe_instructions` collection, with a one-to-many from `recipes` to `recipe_instructions`. This one to many interface would have to render the values inline to make it a "repeater" field

I am not sure if this is actually the way that I (personally) see the structure of the data. I understand that you could have a list of all 'recipe_instructions' in a collection but, in my use-case, all instructions are unique and not re-usable. If you put all those instructions in one collection, an instruction from 1 recipe has nothing to do with an instruction that is from another recipe.

So I think the data should be structured in a way that the recipe instructions are divided into groups.

I made these images the way I see it:
![01-data-structure-recipes-instructions](https://user-images.githubusercontent.com/10308155/51981611-ead30080-2493-11e9-8829-107d8d3b9118.jpg)

This is the way I see it how the data could be stored. But in my CMS I do not want to select a recipe instruction group per recipe. I want to create it and manage it directly when I am adding a new recipe.

Like this:
![cms-recipe-example](https://user-images.githubusercontent.com/10308155/51982080-4ce03580-2495-11e9-8ded-8faba4ef6f1d.jpg)

This is the simplest version of the repeater field for unique content such as recipe instructions. For recipe ingredients this could look more like the image above made by @benhaynes. Where the category name could be the name of an ingredient, because ingredients are re-usable among other recipes.

Hope this makes any sense.

**Comment by jimbatamang** [comment]
Eagerly waiting this feature, any eta?

**Comment by benhaynes** [comment]
Once all the core interfaces are stable then this is first on our list! Just need to dev time to get the main interfaces tested/documented first.

**Comment by benhaynes** [comment]
In the meantime, a M2M will give you the same functionality... just in a modal.

**Comment by Log1x** [comment]
@rubenmeines hit it on the nose as far as the concept goes. How it's designed could be more-so what @benhaynes had in mind initially– but honestly, I don't really care as far as that is concerned. I would just like it implemented.

But the recipes is a good example. The repeater should be able to hold any kind of other field inside of it and have it repeated.

So say I have a repeater labeled **Services**.

It would go:

**Services**
- Service
  - Title (Text field)
  - Icon (Image or Code Editor for inline SVG)
  - Description (Textarea Field)
  - Price (Number field)

- Service
  - Title (Text field)
  - Icon (Image or Code Editor for inline SVG)
  - Description (Textarea Field)
  - Price (Number field)

[Add Service] ...

**Comment by benhaynes** [comment]
Perfect, great input @Log1x — thanks!! Here's a slightly updated design with collapsing repeater items. Also, didn't we have someone who said they were building this interface to save as JSON @rijkvanzanten ???

![Screen Shot 2019-03-25 at 12 07 25 PM](https://user-images.githubusercontent.com/522079/54935460-bc532e00-4ef6-11e9-9278-372c107785f5.png)

**Comment by rijkvanzanten** [comment]
There's an in the works PR: https://github.com/directus/api/pull/799

**Comment by Log1x** [comment]
@benhaynes looks excellent!

**Comment by tex0gen** [comment]
As soon as this becomes available, I'm full on ditching Wordpress for Directus.

**Comment by stuartcusackie** [comment]
Would this repeater field define a strict structure of fields or would it allow the user to build their own structure from a list of allowed fields?

For example, on Cockpit CMS I can define a repeater field called 'Body'. Then I can define which "sub-fields" are allowed, e.g.: Text (wysiwyg), Text(heading),  Image, Text (embed). This way a user can build their own structure for a post, e.g. Heading, Image, Wysiwyg, Heading, Text, Image, Text.

It's probably not a great example but the structure provides a lot of flexibility.

**Comment by rijkvanzanten** [comment]
@stuartcusackie I think that's more https://github.com/directus/app/issues/1392 territory 🙂

**Comment by stuartcusackie** [comment]
@rijkvanzanten

Thanks for the link. I didn't see that one. I still think that what I'm suggesting is more closely related to this issue than to #1392.

What I'm suggesting is Ia variation of a repeater field. Not a grid layout.

**Comment by rijkvanzanten** [comment]
Exactly! That's why I thought it was more territory of that two-dimensional one 🙂 That's the flexible one that re-uses post types and lets you setup any order and set of fields. (If you only use one column, you'd end up with what you describe afaik).

They are very different in how data is saved. This repeater will rely on a one-to-many relationship, where any individual 'repeat' is in fact a row in another collection. This wouldn't really work for the flexible one, as you can have any number of fields in use. Instead, it should save as a nested JSON object in a single field to be able to provide that flexibility, which is #1392 will do 😄

**Comment by stuartcusackie** [comment]
Well that answers my question 😄

I hope what I'm talking about can be introduced in #1392 then. I don't necessarily need a multi-dimensional structure, though I'm sure it would be handy. I just want my users to be able to build posts their own way from a list of allowed fields. The 2D layout is something I usually prefer to control in my front-end code.

**Comment by benhaynes** [comment]
Correct me if I'm totally off here, but there are three different interface options:

1. **"Repeater"** — O2M relationship with more of an "inline" editing interface
2. **"Relational Builder"** — Would be the M2X (many to any) relational interface that allows relating items from different collections. This would let you pull in relational items from collections with different schemas (header, image, body, quote, slideshow, module, etc). Benefit of having structured data/validation, etc... and content is "reusable".
3. **"Dynamic Builder"** — This would be similar to the relational builder, but would save data in the parent as JSON. This means that the schema is completely open and can be defined _per item_... but all control/validation would need to be added through this parent interface.

Yeehaw?

**Comment by cesasol** [comment]
I'm back to working with this issue and I think that this Repeater field should be a JSON array inside this table because sometimes the complexity of simple repeatable data structures are not worth setting up database tables for them. For example my specific needs requires a 4th level of data for a simple listing of information so the "inline" editing for O2M is just not something that would be useful in any way. For that purpose I think that the current relationship fields should have an inline option and don't relay on modals, this way it would also fix the issue when you have nested relationships like a "related post" kind of relation where there is a image inside the other post and you can't edit that field with the current modal interface
And with the same thinking this would simplify the way that this could be a "flexible repeater" like cockpit's where you can have different schemas to choose from

**Comment by benhaynes** [comment]
Hey @cesasol — I think eventually we'll have all three "types" of repeater interfaces. We (internally) can take on the relational O2M version (not for a while, but we can do it)... and would love if you wanted to look into the JSON version! 😄

**Comment by benhaynes** [comment]
Just a slightly updated design mock:

![Screen Shot 2019-05-15 at 8 02 47 PM](https://user-images.githubusercontent.com/522079/57817264-96a31200-774c-11e9-83cc-5c7f8fa0ac52.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
