### ISSUE TITLE
Add file upload on drag and drop on the tile listing view

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#122]
Should only be active for directus_files. Has to be some proprietary logic on the tile listing.

**Comment by benhaynes** [comment]
My thinking here is that since we have a global DAM (File Library) we should accept file uploads _anywhere_ in the system. If you drag to the page, we have a global app outline style and a dropped file uploads and shows a notification when complete with a link to view the Directus Files detail.

If you drag to a specific Interface with drag-and-drop then that would take priority and the same style/effect would be surrounding the interface only and would not bubble up to the app level.

**Comment by rijkvanzanten** [comment]
I'll think about the idea of having the dropzone in the whole app at all times. It could work seeing we only have 1 place to store files, but I'm not sure if it makes sense from a UX perspective.

**Comment by benhaynes** [comment]
Perhaps not, but if someone is dragging a file to the CMS, they clearly want to upload it. The question is _where_ are they expecting that file to "go"? If we can make that clear through the UI styling, I think it could work well. But open to discuss!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
