### ISSUE TITLE
Non-branded loading animations

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1225]
We want to keep the "loading" animation standard ([not customized](https://github.com/directus/app/issues/1105)) since it's an important system effect. I think we offer two Global Settings (dropdown of options in case we add more in the future or boolean if we know it will only be these two):

1. Running Rabbit (default)
2. Spinner (non-branded)

Each works the same way, only appearing/animating when something is happening. If the project is using a custom logo, then the animation (rabbit/spinner) fades in over the logo temporarily when activity is taking place.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by FRSgit** [comment]
Recently I came across on #1105 because I had need for changing default rabbit to something customized & animated. Unfortunately AFAIK it's not possible with current directus which is a pity :<

From my perspective it would make sense to, at least, introduce some "loading" class on e.g. body element, so it will be possible to create your own "loading effect" with use of some custom CSS styling, what do you think?

**Comment by benhaynes** [comment]
I like the idea of a non-branded spinner option, but once we have that you would be able to override this in the App's custom CSS. Right @rijkvanzanten ?
