### ISSUE TITLE
Make File Preview interface work outside of directus_files

### ISSUE THREAD

**Issue by creazy231** [directus/app#1229]
# Bug Report

## Steps to Reproduce

1. Go to `collections` and create an new entry using the `File Preview` component.
2. Try to add a new article (in my case) and open the console to view the error.

## Expected Behavior
editable file preview

## Actual Behavior
nothing - can't even upload an image

## Technical Details

- Device: Desktop
- OS: MacOS
- Web Server: MAMPP
- PHP Version: 7.2.10
- Database: MySQL
- Install Method: master manually config

**Comment by FRSgit** [comment]
Hey, is anybody working on this?

**Comment by rijkvanzanten** [comment]
Not currently @FRSgit. You wanna take a swing at it? 🙂

**Comment by FRSgit** [comment]
Thinking about that since having image editor in place would be nice for my use case. Do you have any clues for me where to start?

**Comment by rijkvanzanten** [comment]
This is where the actual Vue component is that builds up that file preview interface: https://github.com/directus/app/blob/master/src/interfaces/file-preview/input.vue

Right now, it's relying on a couple proprietary names / fields that only work in directus_files. For example, it [reads the values of the other fields on the page](https://github.com/directus/app/blob/master/src/interfaces/file-preview/input.vue#L144) to extract what kind of image it is, those fields only exist on the detail pages of directus_files.

I think we should be able to extract most of the information it's currently pulling from the other fields from the value (`this.value`) of the file itself which in turn should decouple it from the directus_files collection

**Comment by benhaynes** [comment]
We can also add interface options to allow the user to set/map any other needed fields. But I prefer Rijk's method of getting it from the main value since that's more "set it and forget it".

**Comment by FRSgit** [comment]
**Sorry for the long comment!**

Okay, I investigated the issue a little bit and have few conclusions. 
First of all mine use case was indeed (as in issue #1425) something which should be handled by `file` interface - there is need for having file uploader which allows user to add image editor functionality.
But then, the question arises - what exactly is `file-preview` interface in the first place and if it's not just a `file` with `value` set and e.g. option `displayName` set to `preview`.
Or (other way around) maybe it's separated **extension** of `file` interface, which inherits some of the logic, or just uses `file` component internally (for handling initial situation - when image is missing)?

I don't know if I'm missing something or just `file-preview` in current shape was something built temporarily, but I think it should be (at least partially) redone considering one of two possible paths of development described above. Please drop a comment if you think I got something wrong and/or if you have any suggestion which way is closer to what you had in mind when creating this interface.

**Comment by rijkvanzanten** [comment]
> But then, the question arises - what exactly is file-preview interface in the first place

The files endpoint returns information on the file in a `data` key. In order to preview this file on the details page for directus_files, an interface was needed that wouldn't upload _to_ directus_files, but instead would _be_ a directus_files data point. Later, this "file-preview" was extended with extra functionality like the ability to crop and rotate, and was extended to save to directus_files in a non-"standard" way. This is what caused the incompatibility of the file-preview interface with regular collections. As far as I'm aware of, this is the only interface that does not work outside of the system collections.

**Comment by FRSgit** [comment]
I think I don't quite get that yet - shouldn't `interface` always include both field edit & display modes?

From my perspective `file-preview` is a special display mode of `file` interface. It should be available together with currently used `v-card` (maybe there should be some kind of a switch to toggle between `v-card`/`v-image-preview`?).
In file directory it would still be visible the same way - because of mentioned above switch. The only difference would be that `file-preview` wouldn't be a separated interface, but a component (like `v-card`)

**Comment by rijkvanzanten** [comment]
Ohhh I think I'm getting on the same page now. You're saying that this should be the `readonly` mode of the regular `file` interface? That makes total sense!

**Comment by FRSgit** [comment]
Yup, that exactly what I had in mind! So I understand you agree on that? 😄 So, at first I would move file-preview to components and do any necessary changes to make it available for more general use. Then, introduce it inside `file` interface - here we need to think of how admin panel user could change `displayMode` of `file` interface - both from logic & UI perspective (now I see there is text input option which allows us to change items appearance, is this some previously agreed pattern I should follow)?
Next, if everything work in general usage I will tackle introduction of `file` interface inside of `file directory`, so I know that component have everything we need.

Sounds good?

**Comment by FRSgit** [comment]
And in connection to #1463 I think I can handle that one too, but don't know if it should be done in separated issue. Also, do you have already, anywhere in directus, the lightbox or similar functionality?

**Comment by rijkvanzanten** [comment]
Another question: the current "file-preview" has the option to change the file that was uploaded (rotate / crop etc). That's not readonly behavior of course. Should we replace the card preview with this bigger image preview that also had the crop etc for "normal" file usage?

**Comment by benhaynes** [comment]
I think we should have _one_ interface for all **single** files, it should show a large (responsive) preview just like the File Preview we have, and have an option to enable/disable the editor. So I think we should combine `single-file` and `file-preview` into one interface.

We should use the "Card" style for **multiple** files... so that they can be dragged into a new order. Or, we could use a more linear "tabular" style for multiple files, since that already support drag/drop and can have an image preview (the only issue is that the image preview is a bit small).

**Comment by FRSgit** [comment]
Okay, so we all agree that `file` and `file-preview` component should be joined - I guess into `file` component (no need to come with different naming).

Also, I don't want to mess here with multiple files at all, AFAIK that's completely different interface and while it could be updated with some changes we are now making for single-file, it's not a priority now.

@rijkvanzanten considering your question - well, I guess we have two options here:

 - let user choose if he wants to use `v-card` or `file-preview` way of displaying file,
 - (preferable by me) stop using `v-card` inside of `file` interface and use `file-preview` there (ofc after some adaptation). Why? Because `file-preview` has better support of handling different file types (has video/audio/youtube/vimeo players), especially when it comes to preview file/editing purposes.

As I said, I would go with 2nd approach and replace `v-card` with changed `file-preview`. And considering `readonly` - well, it will be readonly until user specifically chooses to enable image editing capabilities 😄 

Please, if you agree with that just drop 👍 and I'm starting development 😉

**Comment by benhaynes** [comment]
That's perfect @FRSgit! I agree, we should combine them and only use the larger (and responsive) File Preview UI. We can ditch the `v-card` view altogether in this interface (though I think it might be useful in a different "Multiple Files" interface).

So excited to see this update — it's a really important interface and this will make it much more visually appealing and useful!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by FRSgit** [comment]
Hey, sorry to comment on closed issue, but I wanted to update directus instances recently (and to stop using my 'make file preview work outside of file directory' fork) and saw that these changes never made it to the master branch?
What's the matter - did you have some additional problems when bringing it in? If so, can I help somehow?

**Comment by benhaynes** [comment]
@directus/app-team 🔔

**Comment by FRSgit** [comment]
^up, up :<

**Comment by tiffanynguyen0211** [comment]
^up up UP !

 my team in a hurry to get this feature working, any update when it is merged to master?

**Comment by benhaynes** [comment]
This is open source software, so they're is no official time this will be implemented, unless:

1. An external developer submits a PR for it
2. An external person/company financially sponsors its development
3. We get the app stable (no/less bugs), move on to enhancements, and work our way through the list to this one.

**Comment by alrick** [comment]
@benhaynes I understand the clarification, people seems to have the same expectations for an open-source project than with a licensed one, which I find really out of place but not that surprising.

But in this case hasn't @FRSgit worked on this ? It seems his work wasn't merged into the master branch.

**Comment by FRSgit** [comment]
Yup, I did, even @rijkvanzanten worked to bring this change to master, but I don't know why this branch got lost in the process and wasn't merged :<
The problem is that the [feature branch](https://github.com/directus/app/tree/file-preview) is already outdated, so somebody would need to rebase it into master & resolve all the conflicts (I did it already once and won't have time to do that once again in upcoming weeks :<)

**Comment by benhaynes** [comment]
Ahh, that makes sense. Yeah, most of our team was super busy up until about a month ago (school, work, etc), so our time was just keeping things afloat (no time for properly reviewing/merging PRs). But now everyone is back on things full-time... and we'll see about getting that PR checked out ASAP.

@rijkvanzanten — any additional thoughts?

Sorry for the confusion! :)

**Comment by benhaynes** [comment]
Rijk and I have been discussing this PR/issue, and here are my thoughts:

We need to focus on reducing code/feature complexity in Directus now, and so instead of having multiple interfaces that do the same (or similar) things, we should combine them to have a single, powerful one. This is a bigger change, because these two current interfaces are very different. Here is what I propose for this master file interface:

* Shows a file based on the `pk` value (not from sibling fields)
* Displays the image in a consistent way, nice and big like file preview
* When no value is present, allows users to upload, select-existing files
* Has an option to enable/disable editing the source file (eg: crop, etc)
* Includes all the other interface options we want/need (limit mime type, limit size, etc)

Right now, `file preview` has no upload/select option and pulls from sibling fields... `file` has no edit option and pulls from the pk value. So this is a bigger refactor that will take place in a few weeks when we move into the _Core Base Component Refactor_ phase. So this will be in limbo until then.

**Comment by rijkvanzanten** [comment]
The changes from the mentioned pr take the functionality to 80% there, as Ben mentioned, we'll move that over and clean it up when extracting the base components

**Comment by FRSgit** [comment]
Thanks for update! As @rijkvanzanten said this whole PR was about bringing `file-preview` & `file` interfaces together, we have even talked about doin it @benhaynes in this very topic in April 😄As I said, I won't have much time next few weeks, but if you need a hand after that time - give me a sign. Cheers!

**Comment by benhaynes** [comment]
Haha, yeah... open-source is a dynamic beast. Hard for me to keep up with it all sometimes. We'll get there! Just want to make sure we do it right. :)

**Comment by jacobrienstra** [comment]
hello idk how useful this would be to a general user base but at least for me, it'd be awesome if we could add a feature to choose which aspect ratios to include in the crop editor, and even force an aspect ratio. i think it'd be pretty easy to add code wise, just an option in the interface chooser, and it's really useful when rendering images in a dynamic layout to know what the relative size is

**Comment by rijkvanzanten** [comment]
You mean this thing? 😉 

![image](https://user-images.githubusercontent.com/9141017/69928847-f6fc6580-148a-11ea-8a25-fbfe95a3009c.png)

**Comment by jacobrienstra** [comment]
oh sorry yes i meant choose which options to include there. like being able to make them crop it to 4:3. or only 4:3 or 16:9. that kinda thing

**Comment by FRSgit** [comment]
Thanks for the input @jacobrienstra - if I understood correctly this feature request has already an issue opened here #1468, please feel free to comment/add your reactions there

**Comment by FRSgit** [comment]
Hey, what's the status here? Can I be of help to bring this feature live?
Recently we have celebrated one year anniversary of this issue 🎊

**Comment by benhaynes** [comment]
@rijkvanzanten is in the process of refactoring our core components and interfaces, so it's likely to get added to our work docket in the next few weeks. :) Rijk would know if there's a way for you to help/contribute to his work...
