### ISSUE TITLE
🐰 Design Update — Community Feedback

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1236]
# 🐰 7.1 Design Update — Community Feedback
This ticket provides place to gather community feedback for our upcoming UX/UI update planned for v7.1. **Anyone is welcome (and encouraged) to post thoughts, comments, criticism, feedback, emoji, or ideas to this issue's thread.**

## What problem does this feature solve?

* Simplify the overall Application structure
* Abstract all (core and extension) pages into modules
* Allow for dedicated navigations per module
* Modularize the Info Bar content
* Apply consistent styling across the Application (eg: new styleguide)
    * Improve legibility and internationalization support (eg: RTL)
    * Improve theming by standardizing palette
    * Reassess component sizing for better responsiveness (eg: breadcrumb)
    * Simplify the form grid and standardize input styling
* Refactor of all keystone core components

## Would you be willing to work on this?
I already have! Below are the _initial_ design mockups for community review. These are works-in-progress and subject to change. 

> The primary architectural difference in the 7.1 UX is that left-sidebar has been split into a Module bar and a subordinate Navigation bar. This means that modules like File Library, User Directory, Activity, Settings, and any custom Module Extensions (previously "Pages") will have their own dedicated navigation.

![directus 7 1 browse](https://user-images.githubusercontent.com/522079/50868520-ed9f7180-137d-11e9-9484-e4a990f6a1fa.png)

![directus 7 1 detail](https://user-images.githubusercontent.com/522079/50868544-03ad3200-137e-11e9-861c-c421ef064e66.png)

![directus 7 1 detail info](https://user-images.githubusercontent.com/522079/50868566-1f183d00-137e-11e9-932c-05f63bf472cd.png)

![directus 7 1 browse files](https://user-images.githubusercontent.com/522079/50868552-10ca2100-137e-11e9-882f-7198d40aefb7.png)

![directus 7 1 dashboard](https://user-images.githubusercontent.com/522079/50868560-1a538900-137e-11e9-8ce9-83898b3b1858.png)

**Comment by shealavington** [comment]
Will probably need a breadcrumb on the file navigation, this way if you head into multiple folders deep, you can easily come back up the tree without having to press 'back' 4 times, and visually track how deep you are into the file system quickly.

**Comment by benhaynes** [comment]
When traversing folders in the File Library, you're essentially going through nested relationships. I was thinking that all nesting would be visualized in the main breadcrumb, seen above the page title. I like the idea of keeping this all in one place for consistency's sake.

As for the reduced real-estate, it _is_ a big jump — for a 1000px wide viewport we'd be moving from 800px of content to 652px. However we're also limiting the main form grid to 640px wide in 7.1, so it won't be much of an issue on the Item Detail page. I do concede, however, that the horizontal space is always nice on the Item Browse page — since it means you can have more field columns visible at once.

I wonder if a global "distraction free mode" on the would solve this. It could be a top-level button to temporarily expand the page container edge-to-edge similar to what we'll be doing for smaller responsive viewports. That might be nice for authoring content in full-screen and getting the _most_ screen real-estate out of the browse pages or custom extensions. It would also be fairly easy to implement — just need to find an unobtrusive place for the permanent button... or we just make it a keyboard shortcut! 😄

**Comment by honzabilek4** [comment]
I totally love it! 🎉  When will be the release date? 😆 😆 
As for the details, I can imagine the menu being collapsible, so you can make yourself more space when you need it (ie display more columns in the item list etc.)
One tiny detail I don't really like is the profile image in the bottom-left corner. It's a place where I wouldn't expect it at all and It kinda doesn't fit there for me, though I appreciate the idea. However, it might need some time to get used to it.

**Comment by benhaynes** [comment]
Thanks @honzabilek4! Originally we were planning on starting the refresh next week, but I'm concerned that this will put our App bug tickets on hold for too long. So we might focus on App bugs next week and start the refactor after that.

The nav bar could be collapsible down to the icons only (64px) just like the left-most module bar — that would keep things accessible and give more space. I don't mind that idea!

As for the user menu, that's where it is now and has always been! 😄 Any thoughts on where else it could go? It's a "top-level" item so I think it makes the most sense in the module bar (where it is now).

**Comment by honzabilek4** [comment]
I see. I just wasn't used to have a photo there 😄😄.  Or maybe the cogwheel above it was the thing that felt a little out of place. I wouldn't mind moving it up together with the other icons as it'll be a place to go for many admins while setting up the collections, roles etc. Or do you have some specific interaction on it in your mind?

**Comment by rijkvanzanten** [comment]
@honzabilek4 has a point; settings is nothing more than a module that's only accessible by users in a specific role.

**Comment by benhaynes** [comment]
I see your point — and it does make sense to have the Settings up with the other modules.

I was trying to differentiate Settings and give it a reliable (muscle-memory) place in the App since if it's up in module-land it might be _harder_ to find since it's placement would differ based on module count/order/extensions.

Let me know your thoughts on that... but I'll plan on shifting it up with the others!

**Comment by MartinN3** [comment]
On new desings i don't like default folded search bar in on large display. Filtering is most important in directus because edit(item detail) doesn't open in modal so you dont know where you ended scrolling when you go back on list view - and thats good habit to solve it by first filtering data and not by scrolling down for minute. 

I am stunned by looks of directus. I don't really think there is need for major change. Just maybe fixing some of those nonbreaking visual bugs.

You have done great job, with so many UI components and even harder things like nested modals scrollbars, responsivity, selects, lists and app is so swift. Not even corporations with piles of money have ui so smooth with all those managers, testers and analysts.

**Comment by benhaynes** [comment]
Thank you for the feedback and kind words @MartinN3!! It's a labor of love, so comments like yours go a long way. We might even want to quote you on our marketing site if that's OK by you. 😄 

As for the collapsed search input, it's actually no less accessible than now and shows _more_ information. If you click on the magnifying glass icon, the input expands and gets focus... so it's one-click and you start typing. In the current App, you click the search input to focus it so it's still one click to type. The only alternative I can think of is to give that input focus on page load — which I don't mind — or to assign a keypress to search so you can hit that hot-key and start typing.

Advanced Filtering is also the same as it is now, one-click to expand the menu, and then you can choose a field to filter on, and choose a filter type. A few more steps, but this is a power-user feature and each filter needs to be configured a bit more.

What are you thoughts on all that?

Lastly, as for "going back to where you were" after viewing an item detail, that's been bothering me for a while too. 😉 ... some thoughts:

1. Ideally we get this [item highlight ticket](https://github.com/directus/app/issues/1035) added in
2. I also would like to get a [Split View Layout](https://github.com/directus/app/issues/783) built so that you never have to leave the page you're on. The split has the added benefit (over a modal) of letting you browse other items at the same time. Haha, @nitwel — you interested? 😉

**Comment by Nitwel** [comment]
Would be easy if I would know how to update data from a layout and how i import the needed interfaces. But then it would be pretty easy.

**Comment by ceruulean** [comment]
It looks pretty slick! :sunglasses:
I think the header text should line up with the blocks (like it does when you scroll down and it becomes a sticky menu)
![image](https://user-images.githubusercontent.com/41603229/51268003-9a807c80-1984-11e9-9b82-be36015f5351.png)

The profile pic looks a bit weird, but I think it's because it's flush with the taskbar and crammed in the corner. Maybe circular profile pics are popular because it creates gaps?

**Comment by adevade** [comment]
I've just found Directus and I'm already in love. This new design looks beautiful! ❤️ 

@benhaynes One thing I was thinking about was that you maybe could de-emphasize the big red delete button on the edit pages. Now it stands out as the primary action of the screen, which it probably most often isn't. 

If the button looked more muted (maybe like the search icon in your other screenshots), and when you clicked it you get the confirmation modal (like you get in the current version). This modal could then be updated to have the red warning color on the primary button, instead of a regular grey button. 

![50868544-03ad3200-137e-11e9-861c-c421ef064e66 1](https://user-images.githubusercontent.com/1066486/51285978-46f84800-19f1-11e9-803a-6a67c9b3a59b.png)

I know the current design is the same, and I think the same applies there.

**Comment by benhaynes** [comment]
Hey @adevade — that's a very good point! Now that I've had a few days away from the design I see exactly what you mean. I'll look into having the color on hover, or some other way to have it not stand-out so prominently. I agree that the confirmation modal can have the red to reenforce the seriousness.

Also, these deigns are already a bit outdated since we're using the 'trash can" icon now too. I'll get another round or two of updates in Sketch and then I'll re-upload the new designs here for review!

**Comment by binary-koan** [comment]
@benhaynes I've also just found Directus and am loving the possibilities! The new navigation layout looks great! One of the first things that struck me (coming from Prismic by the way) was how the popup menu on the current sidebar is kinda awkward to use and initially feels like a random collection of critical and rarely used items - this design makes way more sense.

I had a bunch of thoughts looking through the screens you might find interesting 🙂 

* Is "Collections" in the sidebar here the title of that sidebar? It confused me for a minute because it looks the same as the actual collections - I initially assumed it meant you could group collections with dividers between them so "Collections" was a placeholder name for a single collection in the first group. If that makes sense
    ![](https://user-images.githubusercontent.com/522079/50868520-ed9f7180-137d-11e9-9484-e4a990f6a1fa.png)
* I wonder if a green save button and a grey delete button would look any good? There's not a lot of colour on the page at the moment so it would be nice to add a splash or two to make primary actions like that stand out
* Is the icon at the top of the right sidebar "expand"? I just realised that's what it might be after thinking it must be something to do with HTML code this whole time 😅
* In general the new interface seems particularly icon-heavy. That's not a bad thing, but it does mean when I first looked at the screenshots I was a bit overwhelmed having so many icons to work out. For example on a collection index page, filter is three lines of different length, move rows is two lines of the same length, the sidebar has another two horizontal-line-based icons, etc. I'm more used to it already having looked through the designs more, but that was my first impression

**Comment by benhaynes** [comment]
Hey @binary-koan — excellent feedback, thank you! I agree that moving to this high-level module (and therefore exposing some of those previously hidden important pages) will improve the UX quite a bit. Some responses to your thoughts:

* The nav's top `Collections` item might be removed, but it was my initial attempt to be the "landing page" for the module. So for the Collections module it would take you to the Collections listing (`/collections` now), for User Directory it would be an "All" instead of a specific User Group, and for File Library it would be the root Storage adapter. Basically it's the page we show before the user has clicked into a subordinate nav item. Does that make sense?
* Yeah, we've been messing around with using green (or our blue accent) for save and keeping delete gray until hover... ultimately all colors will be theme-able, so we need to decide if those colors will be forced (for UX reasons) or will simply follow the project theme's accent color (might be weird if their use red/orange/yellow). I'm a fan of keeping the default theme (seen here) super simple and design agnostic... but maybe I've gone too far. 😉 
* Haha, yeah — it's supposed to be "expand" but the Google Material Design set we use [only has that as vertical](https://material.io/tools/icons/?icon=unfold_less&style=baseline). We'll definitely swap that out for something more clear, or remove it entirely and just have the child modules expand and an "X" close the pane.
* Great feedback! This was quite intentional as Directus is 100% onboard with i18n. We will have our tooltip system for hover text, and will continue to tweak the icons to be clear and intuitive. Our current version has a lot of text to explain things, which has the following problems:
    * We need to find people to translate all that for every language!
    * When we add/update text in the design then all the existing languages are out-of-date
    * A descriptive word can be wildly different lengths in different languages... a problem when the text is in a confined space (eg: button, sidebar component, etc)
    * Icons work pretty well with this "square grid" since they can be centered — which helps make RTL a bit easier (we hope!).


Again, really helpful, thanks. I would love to hear if these answers seem like the best approach!

**Comment by binary-koan** [comment]
Thanks for the response @benhaynes!

* Hmm, so the same button in different sections could actually do one of a couple of things? (either shows a list of the types of things in the category like for collections & module extensions, or shows an unfiltered list of the actual content like for users). Off the top of my head I wonder if just changing the text to "All Collections" or something would make it clearer
* It does make sense to focus on the themeability! In my opinion the lack of colour does make the default theme lean too much towards utilitarian rather than enticing, but fair enough if that's a deliberate tradeoff 😄 I guess ideally I'd want separately configurable primary/success/warning/danger colors
* Haha I see, I've definitely done similar things trying to make Material Icons fit my use cases ...
* I18n is a great point, I didn't think of that! IMO tooltips will be really important so I don't see how it solves the "there are too many translation strings" problem, but it totally makes sense to minimise layout changes between languages

**Comment by benhaynes** [comment]
Of course! All important things to figure out before the refactor starts next week!

* "All Collections" sounds like it's the items from all collections... when in reality that would be more of a listing of collections. Perhaps this page/link is not needed though? It only seems useful if it adds new info beyond the icon/name already in the nav bar below. If we _don't_ have this link, then the question is what opens when you click the "Collections" module? Just the first collection? Nothing?
* We're still discussing how the themes would work, allowing total customization with hex values or choosing a palette and light/dark mode then extrapolating the rest. The CSS variables can easily be updated manually for total control, so it's about finding a balance between customization and not having admins ruin the UX/UI accidentally.
* I think I'd like to get rid of this Info Bar section... it takes up a lot of room and only toggles the bar. I think we can find a more elegant way to toggle using the Info components themselves.
* Very true — we'll need 100% coverage for tooltips so I guess we'll need the translations either way. But the icons still solve the layout issues.

**Comment by dev7ch** [comment]
Looks Very Coool 👍 
just a thought, why not putting top breadcrumbs under the title as they have the same color the the number under "All items"

**Comment by adevade** [comment]
@benhaynes Another thing I noticed is that _VIP Members_ is at the bottom of the menu. Doesn't it make more sense for bookmarked items to be placed at the top, since you're probably using them more often?

**Comment by benhaynes** [comment]
A good point to raise @adevade!

My thinking here is that the main list of collections doesn't change (often, at least), and we are simply _appending_ new bookmarks to the end of the list. Bookmarks are subordinate/secondary to the main navigation — and if you created a lot of bookmarks, suddenly you could push the main nav off the page (below scroll).

Another option I just thought of would be to show bookmarks nested underneath the collection they belong to, allowing for accordion style collapsing. Then we could maybe avoid choosing one over the other and keep similar links grouped.

Thoughts?

**Comment by ceruulean** [comment]
I think the original breadcrumb is better, because the expected flow of information is top-bottom. The dark header indicates where the item table starts. The count number is related to the search bar, not the collection breadcrumb. The reversal of dark and light text positions differentiates the space. We are conditioned to expect the latest breadcrumb item to appear below. If there's ever a need for an extensively nested breadcrumb that stretches far right, it will eventually collide with the item count and have the same color.

Could bookmarks have their own spot in the bunny navigation strip? Assuming 1) each user could make unlimited bookmarks, 2) each user has their own preference on whether they display main collections first or bookmarks first, 3) Therefore it is better to take the bookmarks out of the collections flow

**Comment by rachelsun59** [comment]
@benhaynes I think this is a good idea in terms of hierarchy of the page and visual consistency. However, I am not sure if we want to have the _VIP MEMBER_ to be related to the _All Items_ on the right side. Since All items is more related to the search widget on life side.  Also since our eyes read the page from top to bottom and left to right, if so it seems like the page is about _members_ not _VIP MEMBER_ . Possible solution could be: we change the color of _All Item_ to be more consistent with the search widget and keep the original design of the breadcrumb.

**Comment by dev7ch** [comment]
![image](https://user-images.githubusercontent.com/15183757/52519654-05109980-2c5f-11e9-8669-f728524eabce.png)

 when i was thinking about breadcrumbs and top layout i habe a vision of sth like this ... mmh but yes, regarding from the logical term breadcrumbs may should be on the top.

see the visualizations attached, maybe the can help:

<img width="964" alt="bildschirmfoto 2019-02-09 um 11 33 44" src="https://user-images.githubusercontent.com/15183757/52519802-3db17280-2c61-11e9-9593-f2a29f1da4fd.png">
<img width="956" alt="bildschirmfoto 2019-02-09 um 11 40 06" src="https://user-images.githubusercontent.com/15183757/52519803-3db17280-2c61-11e9-8983-db3a592f7a5f.png">
<img width="949" alt="bildschirmfoto 2019-02-09 um 11 40 45" src="https://user-images.githubusercontent.com/15183757/52519804-3e4a0900-2c61-11e9-8f9f-a241b15868be.png">
<img width="976" alt="bildschirmfoto 2019-02-09 um 11 48 23" src="https://user-images.githubusercontent.com/15183757/52519805-3e4a0900-2c61-11e9-9dd9-51fb9b33e69f.png">

**Comment by dev7ch** [comment]
Some thoughts to bookmarks and icons.

> eyes read the page from top to bottom and left to right. 

![image](https://user-images.githubusercontent.com/15183757/52531345-d9032000-2d13-11e9-8439-4f1924f5ecd8.png)

Actualy i realized after a few days testing that there are bookmarks.

I when i read from left to right on top there are a lot of mixed functions and information availiable i have doubt that human mind will instantly process them correctly, in particluar the user is guided by the black nav list bar to the bottom and start processing the logic and structure of the application.

Just a thought:

Why not set a title "Bookmarks" with icon under collection followed by a CTA e.g. "Set bookmark here"

- A flat hirachy of bookmarks would be better imo, assume the collection three becomes nested.
- the users would instanly know on the first visit and before reaching the bottomt, that you can set bookmarke.
- the icon on the top could be removed or replaced

**Comment by benhaynes** [comment]
Thanks @dev7ch — these are all great points! Some of my responses/thoughts:

* Hierarchically I agree that breadcrumb should go above, so maybe that's the right decision. 
* The icon just left of the header/breadcrumb is quite important (eg: back arrow on responsive), so I think all of this alignment needs to consider that. The main question is do we group the title+breadcrumb and align that to the icon, or align the title only and push the breadcrumb to the space above. Small but important details!
* A big part of navigation (IMO) is muscle-memory. So I think keeping nav item positioning as static as possible is a good thing. So I agree that nesting bookmarks isn't the best idea and why collapsing _might_ not be the best idea (though I'm not against trying it out). This is also why I think that bookmarks should go below the top-level collections.
* I like "Create a Bookmark" in the nav instead of the header (we used to have that), but my issues are:
    * You always have a "Bookmarks" section and button even if you don't have bookmarks
    * You are bookmarking the "page" (middle section), so it feels more intuitive to me to have that CTA there
    * All nav items are links, while all header buttons are actions. This isn't a huge point, but "Create Bookmark" makes a bit more sense in the header because of that.
* I will say that the most "precious" space is the horizontal header space... so moving the Bookmark icon to the nav bar would help there too. It's that eternal battle of form/function!
* I do agree that we should label the "Bookmarks" section in the main nav... that isn't clear enough by simply delimiting with a line.

> Why not set a title "Bookmarks" with an icon under collection followed by a CTA e.g. "Set bookmark here"

Are you saying the CTA would be at the top under "Collections" or below the actual collection Items? We've been discussing if the need/purpose of the "Collections" link at the nav top... it's basically there to represent the landing page for the module (before you click on an actual collection).

Also, let me know if it would be easier to generate community mockups if we made the master Sketch file available. 😄

**Comment by ceruulean** [comment]
[Figma for showcasing design?](https://www.figma.com/)

Also my initial idea for bookmarks:
![image](https://user-images.githubusercontent.com/41603229/52741715-a5d2c200-2f9b-11e9-811c-419d13517e6b.png)
* Intuitive (especially for tablet/touchscreen, it's easy to reach with left hand)

But if you want to keep the current screen estate you could do something similar to the project switcher:
![image](https://user-images.githubusercontent.com/41603229/52741764-c4d15400-2f9b-11e9-93f5-644af37de9f1.png)
* More control (for example, admin wants restricts access to all collections and only show bookmarks to certain user roles)

**Comment by benhaynes** [comment]
Interesting ideas @ceruulean!! 

We've been looking into Figma and in fact imported all of our Sketch files there to try it out. We've been liking it, but since it has no way to export back to Sketch, we'd be "stuck" with it if we started making edits in there. Until we've done a bit more research (and Figma is a bit more mature) we'll stick with Sketch.

I think the left module bar would be splitting different data — so I'd rather not have bookmarks there.

I actually don't mind the dropdown approach... but my main concern (actually with _both_ of these options) is that if the user is navigating collections as usual and they want to view a bookmark... then need to make an extra click to see/access those bookmarks. Still, I think we should look into the dropdown idea a bit more.

Thoughts @rachelsun59 ?

**Comment by benhaynes** [comment]
Most of these changes have been merged and this ticket is closed, but we can still use this as a place to discuss this design overhaul for the time-being.
