### ISSUE TITLE
Unable to resize collection columns

### ISSUE THREAD

**Issue by dougludlow** [directus/app#1240]
# Bug Report

We are unable to resize columns. I'm using Firefox on a mac, a coworker is using Chrome on Windows. 

## Steps to Reproduce

1. Using Firefox on a mac or Chrome on Windows, login and choose a collection.
2. Hover over the column boundary in the header and attempt to drag.
3. Notice that it doesn't drag.

## Expected Behavior

Users should be able to resize collection columns regardless of what browser/os they are on.

## Actual Behavior

Dragging a column boundary does nothing.

## Other Context & Screenshots

I was able to get it to drag on Chrome on a mac.

## Technical Details

- Device: Desktop
- OS: MacOS
- Browser: Firefox 66
- Directus App: directus/app:latest (probably 7.0.13)
- Directus API: directus/api:latest (probably 2.0.13)
- Install Method: docker

**Comment by rijkvanzanten** [comment]
Drag and drop seems to be super buggy on Firefox 🤔 

We'll have to implement some workaround where it's using the document to extract the mouse position on drag, instead of relying on the (spec) clientX value in the drag event.

https://stackoverflow.com/questions/23992091/drag-and-drop-directive-no-e-clientx-or-e-clienty-on-drag-event-in-firefox

**Comment by benhaynes** [comment]
Can confirm that this is a FireFox browser bug that is being tracked on their side. I'll close this since there's nothing (non-hacky) that we can do. Hopefully FireFox gets this resolved soon!

https://bugzilla.mozilla.org/show_bug.cgi?id=505521
https://bugzilla.mozilla.org/show_bug.cgi?id=1428225
