### ISSUE TITLE
Interface: Tags not displaying thumbnail_dimensions correctly

### ISSUE THREAD

**Issue by WellingGuzman** [directus/app#1249]
# Bug Report

## Steps to Reproduce

(On development)

0. Update the database to the latest in `master` branch (Also update the schema, it adds the `thumbnail_dimensions` to the `directus_fields`)
1. Go to Admin Settings
1. Click on Global Settings
3. Scroll down to `thumbnail_dimensions`
4. See the default `200x200` value, split by characters

## Expected Behavior

200x200 be a single value.

## Actual Behavior

Value split by characters

## Other Context & Screenshots

<img width="325" src="https://user-images.githubusercontent.com/1531291/51061690-7f9bba00-15ca-11e9-8da9-0d9b39cf4cbe.png">

## Technical Details

- Directus App: development/master branch
- Directus API: development/master branch
- Install Method: Cloned `master` branch of `directus/api` and `directus/app`

**Comment by theharshin** [comment]
The issue is with reading the values from response.
In some cases, even if the `type` is set to an `array`, the API is returning `string` as response. 
For example in this case, the field `thumbnail_dimensions` is returning a `sting` instead of and Array.
![image](https://user-images.githubusercontent.com/7118937/51462822-9ccd4700-1d87-11e9-816a-3d1391b8b779.png)
![image](https://user-images.githubusercontent.com/7118937/51462916-d3a35d00-1d87-11e9-9088-c214abf0b831.png)

The condition is set as
`const array = [
        ...(this.type === “array” ? this.value : this.value.split(“,”))
];`

So in this case,it gets converted to an array of characters.

The other issue with interface is, 
It removes the first & last value from an array if wrapping is on, without explicitly checking if the values are blank or not. So if the values are imported and not entered via interface, it may not contain leading and trailing commas hence it removes first and last tags. This happens in default collection of `movies`.

**Comment by benhaynes** [comment]
@WellingGuzman — has this array/code/json response been fixed? We want to make sure that data is always returned appropriately based on the type. If this is _not_ fixed we should open an API ticket to track it.

@theharshin @rijkvanzanten  — since the "wrapped" values are not as common in CSV, perhaps we should consider not having that default to on?

**Comment by theharshin** [comment]
@benhaynes As you said, if both the above points are fixed, interface may work properly without applying a patch. 
But in a case where wrap is manually turned on, and data is imported instead of entering from interface, it will still create an issue. So I've created a pull request of a fix. 
I think this fix will take care of all the situations.

https://github.com/directus/api/pull/719
