### ISSUE TITLE
Custom login background

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1255]
### Would be super sweet. 🔥
![screenshot_2019-01-16 directus](https://user-images.githubusercontent.com/22577866/51250848-07e9d880-1998-11e9-8a30-aeccbdc080a6.png)

**Comment by Nitwel** [comment]
Hmm, thats true, maybe, when there would some bg. already available, the usage of this feature would increase bcause it would only be 1click and you would not have to search for an image first.

**Comment by rijkvanzanten** [comment]
I love this 😍 

As ben mentioned, this has to come from the API, so we can dynamically change it based on the selected project. 

We already want to support the custom logo on the login screen, so we could fairly easily allow a second file input for the background!

**Comment by rijkvanzanten** [comment]
Couple questions up for debate

* Should the background image automatically get the smoke overlay?
* Should we allow the login view to align _left_ instead of center?

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/9141017/51256791-3c4b9d80-1974-11e9-92a8-91175f95779e.png">

* Should Directus have a "directus default" or default to the gray color?
* Should the user be able to set a different login background color in case no image is being used?

**Comment by benhaynes** [comment]
As with most things in Directus, my preference is to allow for customization with some design "guide-rails" in-place to ensure no matter what the admin does things look good and maintain proper UX. Therefore I vote for always centered and with a dark-gray overlay for images. I _do_ like the idea of allowing admins to choose a solid color in the background (instead of an image)!

**Comment by rijkvanzanten** [comment]
We also need to add this information to the information returned by the API. 

@WellingGuzman I think the (added) fields that need to be returned from the API in the `/` endpoint for the project are `project_name`, `logo`, `login_background`.

Project name and logo are already in directus_settings, login_background isn't yet.

(@benhaynes those names sound good to you?)

**Comment by benhaynes** [comment]
Hmm, it seems weird to only prepend `project_` to name and not the others, right? They are all project settings... so I feel like all or none.

Also, I'd like to add an optional public `project_description` (or `description) while we're adding things. That would be used in 7.1 so we might as well add it now.

**Comment by benhaynes** [comment]
Also, would we have a dedicated color for `login_background_color`? Would that pull from the theme?

**Comment by rijkvanzanten** [comment]
Yeah that sounds about right. 

Also, maybe we can use the "module bar" background color on the login screen? That way it's part of the theming

_talking about theming_

If we make the theme setting of a project publicly available, we could use the theme on the login view as well (eg changing the color of the "login" button, stuff like that)

**Comment by rijkvanzanten** [comment]
Closed in favor of #1525
