### ISSUE TITLE
Clearing a field does not activate checkmark to save item

### ISSUE THREAD

**Issue by bignillystyle** [directus/app#1277]
# Bug Report

## Steps to Reproduce

1. Create a new text field with the default settings. I called it 'Phone'.
2. Make a new item, and enter in a value. I used '555-555-5555'.
3. Save the item.
4. Go into the item again. Focus the field and press Command+A. 
5. Press backspace.

## Expected Behavior
Checkmark in the top right becomes active and the record can be saved.

## Actual Behavior
Checkmark in the top right remains inactive.

## Technical Details

- Device: Desktop
- OS: MacOS 10.13.4
- Web Server: Apache 2.4.18
- PHP Version: 7.0.18
- Database: MySQL 5.7.18
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
Hey @bignillystyle! In what version of Directus is this? 

I feel like it might be [this issue](https://github.com/directus/app/issues/1241) that was fixed in the latest version.

It seems to be working fine for me on the current version:

![backspace](https://user-images.githubusercontent.com/9141017/51767092-59861780-20aa-11e9-80e4-783278570c63.gif)
