### ISSUE TITLE
Check if file already exists

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1289]
The [API now saves a checksum of each uploaded file](https://github.com/directus/api/issues/379#event-2107881108). This is a small hash of the actual file that is unique to the file's actual data. Therefore, it would be nice if when:

1. User uploads a file
1. App creates temporary checksum of that file
1. App searches for that checksum in `directus_files`
    * **If it exists**... the App notifies the user and offers to use the existing file instead
    * **If it does NOT exist**...  it adds it to the system like normal

**Comment by rijkvanzanten** [comment]
How does the api generate the checksum? Can we generate the checksum in the same way on the client side?

**Comment by benhaynes** [comment]
Easy peasy...

```
$fileData = base64_decode($this->getDataInfo($fileData)['data']);
$checksum = md5($fileData);
```

**Comment by rijkvanzanten** [comment]
Easy peasy, encoding the whole filecontents and md5 hashing it _on the client side_ :joy:

**Comment by rijkvanzanten** [comment]
If you upload a file > 100mb, won't this completely blow up the server?

**Comment by WellingGuzman** [comment]
It will crash if the memory are not high enough. It takes its time to process, but unlikely to crash if the limits are set accordingly as far as I am concern. We can test this and if there's problem we can see how to handle huge files.

**Comment by benhaynes** [comment]
@WellingGuzman — right, but we should assume that _some_ users won't know how to properly setup the server. Would it make sense to have a safeguard conditional in the API to _not_ checksum large files? Everything I'm reading says that MD5 is a few MBs/sec ... so 100MB file will really slow down the server for a few seconds. The conditional would avoid issues now and we could optimize this for larger files in the future (cron/worker).

Also, maybe it makes more sense to hash new files and do this check on the server only? That way this also works for the API.

Thoughts? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
I'm not even sure if this is a feature that's useful in the first place to be honest 😳

Thoughts:
* If the user adds the same file twice, that's on the user. It's the same as accidentally adding a new item instead of updating an existing item in a collection.
* Storage is very cheap, so having a duplicate file shouldn't be a problem.
* The API can't throw errors/warnings on successful duplicate uploads. You might want to upload a new duplicate (placeholders?).
* Creating the checksum on the client side is unreliable, very heavy, and has a chance to generate a different hash than the server.
* We can't bog up the server for minutes if someone uploads a video file
* Seeing that we really can't performantly create a checksum of big files, it can only be used on smaller files which kind of defeats the usefulness.

**Comment by benhaynes** [comment]
![Rijk the dream crusher...](https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif)

**Comment by WellingGuzman** [comment]
I want to say that I think this is doable, it doesn't take lot of time in the server to calculate, because that data is in memory (_which can be improved, but that's another topic_).

I also don't think it will be unreliable, or there will be a chance to generate different hash, if that happens there's something wrong with the data being sent.

In the browser we can use `FileReader` to read the file by chunks, and using something similar to `crypto` in node, where you incrementally hash the file without bloating the memory and making this a heavy process.

**Comment by rijkvanzanten** [comment]
_They were so preoccupied with whether or not they could, they didn’t stop to think if they should._

**Comment by WellingGuzman** [comment]
@rijkvanzanten I didn't mean to tell whether or not this should be done, I just wanted to suggest that if we want to implement it, it could be done.

**Comment by benhaynes** [comment]
I still think this could be a useful feature  — but we don't have time right now to figure it out (it's definitely not a priority).

Thanks for the insight @WellingGuzman! Let's optimize this later and see if we can get it ignoring duplicates. We can just have the API return the _original_ file object (no new upload) if a duplicate is found. Someday we'll have time for all this fun stuff!
