### ISSUE TITLE
API Environment Configuration Not Found: public

### ISSUE THREAD

**Issue by xyypnoth** [directus/app#1324]
I'm getting an error when trying to open public/admin page after installation:
**error | 8 message | "API Environment Configuration Not Found: public"**

After checking the value of **$configFilePath** in **web.php** I found that the app is looking for:
'api.public.php' file in the config folder, but there's only 'api.php' file. 

Perhaps it is the path problem? My root is pointing to .../public and I didn't make any changes to the paths in .httaccess. Can anyone help?

# Bug Report

## Steps to Reproduce

3. Scroll down to '...'

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch of `directus/directus`]

**Comment by benhaynes** [comment]
Hey @xyypnoth — it seems like you are using the wrong URL for access.

It is looking for the `api.public.php` file because you are including `/public` in your URL (it should be `_`). You need to set the public folder to be the _root base directory_. These should help:

https://docs.directus.io/api/reference.html#project-prefix
https://docs.directus.io/getting-started/installation.html#configure
