### ISSUE TITLE
Ability for admin to delete multiple fields at once 

### ISSUE THREAD

**Issue by Shwetha9** [directus/app#1331]
# Feature Request
Ability for admin to delete multiple fields at once 
## What problem does this feature solve?
If I need to delete multiple fields at once, it is much more easier to pre select all that need to be deleted as opposed to deleting one at a time which is not very user-friendly

## How do you think this should be implemented?
Just allow for multiple selection

## Would you be willing to work on this?
Nope.

**Comment by benhaynes** [comment]
Hey @Shwetha9 — this isn't something that we're likely to implement. Deleting fields is a very serious/permanent  action since **all data in those fields is destroyed**. This could be millions of data-points — so we _really_ want to be sure the admin knows what they're doing. If the admin REALLY wants to destroy in bulk they can do that directly in the database (bypassing Directus).
