### ISSUE TITLE
Can't delete M2M items in random order

### ISSUE THREAD

**Issue by theharshin** [directus/app#1338]
# Bug Report

## Steps to Reproduce

1. Create a new collection named `genre`
2. Add some items to it
3. Add `genre` as M2M on `movies` collection
4. In a movie item, add some genres
5. Now try to remove the the `genre` except the last one

## Expected Behavior
It should allow to remove any item irrespective of an order.

## Actual Behavior
You must delete items in LIFO order.

## Other Context & Screenshots
https://www.useloom.com/share/be2ffb10384644df8f3ad84da1f318b8

## Technical Details

* Device: MacBook
* OS: MacOS Mojave
* Web Server: Apache/2.2.34
* PHP Version: PHP Version 7.2.7
* Database: MySQL 5.7.21
* Install Method: Cloned `master` branch

**Comment by samvasko** [comment]
I can confirm this is the case

**Comment by rijkvanzanten** [comment]
The problem here is the fact that the relational items are being fetched and stored multiple levels deep. This creates a circular structure in where the relationship field is copied levels deep inside the main item, which causes the API to update the value double and thus don't delete the item:

```
members (13)
  favorites (o2m) (A
    movie (m2o)
      id: 5
      ...
    member (m2o)
      id: 13
      favorites (B
        movie
          id: 5
        member
          id: 13
```

This can cause all sorts of issues, as `(A` will be in a different state than `(B`.
