### ISSUE TITLE
Strange behavior when update year in datetime interface

### ISSUE THREAD

**Issue by KKAries** [directus/app#1347]
# Bug Report

## Steps to Reproduce

1. Add datetime interface to the collection
2. Create an item, set the datetime field and save
3. Go back to edit the item
4. Click on the year section of datetime field to update year
5. Use keyboard(numbers) to update the year
6. See the year is jumping to some unexpected number

## Expected Behavior
The year can be set by the keyboard.
## Actual Behavior
The year setting is not working properly.
## Technical Details

API 2.0.18 and APP 7.0.18

**Comment by theharshin** [comment]
The issue is with date-fns `format` function. It works for only years between 1900-2099.
So when you write down a year which is not in range above, `format` function randomly puts a year inbetween the above range. This issue is in with creating a new and editing existing date fields.

![image](https://user-images.githubusercontent.com/7118937/53498229-f124be80-3acb-11e9-993c-e62e3ec36040.png)

**Comment by samvasko** [comment]
Entering 2019/02/31 results in 2019/03/31 being stored
