### ISSUE TITLE
Collection Groups

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1357]
# Feature Request
Hey, what about an mixed display type for tables which allows something between a single page table and a list.

## What problem does this feature solve?
Having 2 seperate tables for 1 section.
An example would be that you want to manage a section on your page and you dont want to have 2 seperate tables. For the section you want to have a list of articles but also manage the section color and a background image.

## How do you think this should be implemented?
This could be implemented by displaying the singe page view at the top and beneath it the multi page view, eg. a list. And it would be easy to implement because in the backend it could be saved as to seperate tables but merged to one on the app site.

What do you think?

**Comment by benhaynes** [comment]
Hmm, I'm not sure I completely understand this one. Are you saying this is a new Layout with two listings? Could this be solved by having a relationship, two Admin App tabs open in the browser, or the ["Split View" Layout](https://github.com/directus/app/issues/783)?

**Comment by dev7ch** [comment]
could you visualize that @Nitwel ?

**Comment by Nitwel** [comment]
I had my thoughts on it and another way to allow such feature would be to add groups for collections.

But here is how I imagined it before:

![mixed](https://user-images.githubusercontent.com/22577866/53898832-2768bd80-4039-11e9-9ca0-75f2c4d92de6.png)

**Comment by dev7ch** [comment]
i think i can understand your thought, i was having q quiet similar problem and the provided solution i choosed was haveing still two tables but ...
 - Table Singel Collection (for static infos such as contact info, footer information etc)
 - Tabel Default Collection (Articles, etc)

so think the thing is directus is very database orientated, and collection are currently not nestable (in that case you may could cretae soome magic with relations).

Coz i am wonnndering where to put this table in DB shema 🤔

**Comment by Nitwel** [comment]
I think the easiest way to add something like groups for tables is by having the table name containing a folder name e.g. "group/table_1" or "groupA/groupB/table_2".

With this way the app could convert this to folders/groups of tables.
Another benefit would be, that you dont run in the issue of duplicate table naming / you can create tables with the same name in seperate folders. This would resolve the need for mixed displays because you can create a group containing two tables, one wich is single file and the other is not e.g. you want to manage Articles and also want to manage an image somewhere on the same page (wich would be a single file view) so your structure would be like:

```
Articles
  - settings <-- Single file view with e.g an image or an overall color
  - content  <-- collection of many articles
```

**Comment by Nitwel** [comment]
![WhatsApp Image 2019-03-16 at 14 35 29](https://user-images.githubusercontent.com/22577866/54476036-ff2b4c80-47f8-11e9-95d9-8ba42c9d0218.jpeg)

I´ve made a prototype how I would implement groups in directus.
The above image creates groups using the names of the collections.
What do you think about this way of doing it, any other ideas/ suggestions?
Because I would like to work and implement this feature in directus!

And should there be sub-sub groups and how should these multiple "depths" be implemented visualy @benhaynes  ?

**Comment by rijkvanzanten** [comment]
I like where you're heading with this @Nitwel!

**Comment by benhaynes** [comment]
Hey @Nitwel — so I'm starting to understand what you're describing. First let me outline how I would architect a solution to: https://github.com/directus/app/issues/1357#issuecomment-470187357

* `settings` (a _single_ collection with static fields)
* `content` (dynamic collection of articles)

So, instead of `settings` I would give it a "global" name, like `articles`. Then I would add a O2M to the `content` collection (which we'll call `posts` here). Now when you click on Articles you'd see the static fields followed by a listing of article posts (almost exactly like your design). 

I think the main thing that would make this _look_ better is having a "full width" option for the O2M Interface so that it looks just like a listing layout. This is a great idea and can be added in the 7.1 refactor/redesign (or a PR from you ;) )

-----

Everything else you've described seems like relationships between collections. I hesitate to abstract things to allow for deep/nested collections since that isn't how databases work and I don't want to go down that proprietary road. The main guiding idea for Directus is that we're 1:1 with the database — and we need to be really careful about layering proprietary features on-top of that.

Down to keep discussing! Let me know what you think about my idea above though!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
