### ISSUE TITLE
Deeper joins into relationships for dropdown templates

### ISSUE THREAD

**Issue by Mozz4rt** [directus/app#1402]
# Feature Request
I'm not sure if this would be at all useful.. I'm not the best when it comes to planning how the collections are gonna be designed and related to one another. But you can't see the value of something that is `{{field1.relat1.field2}}` or deeper.
## What problem does this feature solve?
Give the user more freedom when creating it's own collections.
## How do you think this should be implemented?
I'm guessing that you could fit it in a `fields` parameter when making the GET calls.
## Would you be willing to work on this?
Possibly.

**Comment by rijkvanzanten** [comment]
What do you think would be a good median depth to retrieve these kind of values? The problem is that you could theoretically have circular dependencies and therefore infinitely deeply nested structures. We can't fetch all of that.. 

I believe the application fetches the relational items 3 levels deep in general. The M2O interface fetches 2.

**Comment by benhaynes** [comment]
3 seems like a good depth so that you can get fields on a M2M relationship. There will always be a reason for more (or less) so a good default (like 3) seems like the way to go until we have a way to dynamically fetch different depths based on what's requested.

Speaking of, exploding our dot-notation to find the requested depth should be possible. eg:

`news.article_id.title` should explode to array.length `3` and we could fetch that field's relational depth based on that. Thoughts?

**Comment by rijkvanzanten** [comment]
The information is fetched on the page level right now instead of on the interface level. We fetch everything 3 levels deep.

**Comment by rijkvanzanten** [comment]
But yeah, that sounds like the way to go moving forward

**Comment by srjrol** [comment]
I am encountering ~20MB JSON files as a result of this current fetch depth.  There doesn't appear to be any way to control or mitigate this within the app currently.  

I think a solution to this could be to have a variable in the field options to set the fetch depth.  It could have the default of 3 if that seems to be a good median and it should probably have a max.  This would eliminate retrieving irrelevant data, thereby improving load times and data usage.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by ictoi** [comment]
I vote for this to be implemented as we use Directus with deep object relations and on the views I have no other options than copy some parameters on create to parent object. Obviously this is not elegant as the copy is an instance, not a relation.
