### ISSUE TITLE
files interface should default to files listing

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1413]
it's using tabular right now, very annoying to use for the file interface.

**Comment by syslogic** [comment]
It's one of the commits in my recent pull request:
https://github.com/syslogic/directus-app/commit/3b79bd862dc75d11641ebe6c6bf3cb9759d3a700
Still think that the tabular layout is useful, while it's merely images (when being used as media library),
but that might be because the table layout does not feature a visual representation of the image, as it is common for such media-libraries.

**Comment by benhaynes** [comment]
This should be configurable, since the files/images interface should allow for thumbnails on tabular too. Right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
That's correct @benhaynes. Just to clarify, this issue is about the `files` _interface_, not the file library

**Comment by rijkvanzanten** [comment]
I guess this was a configuration error on my side. A fresh install with no options setup works as expected
