### ISSUE TITLE
Left sidebar does not works correctly

### ISSUE THREAD

**Issue by dslpp056193** [directus/app#1421]
# Bug Report

"Three dots" on right side from current user's avatar does not works.
And "help & docs" link refer to `http://current.domain/admin/#/https://docs.directus.io`

## Steps to Reproduce

3. Scroll down to '...'

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/11080873/54878439-0d531b80-4e3e-11e9-8b7f-484e8ec123c3.png)

## Technical Details

- Device: Desktop
- OS: Windows 10.1803
- Browser: Chromium: 73.0.3683.86
- Directus App:  7.0.0? I dont know, where to see this info??
- Directus API: 
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment]
The three dots are there as an indicator that the menu exists. They don't have any purpose once the menu is expanded.

The help and docs link was fixed in https://github.com/directus/app/pull/1403 and will be released shortly.

@benhaynes want to reconsider the dots icon? I'm wondering if the menu is too hidden if we don't have any indicator

**Comment by benhaynes** [comment]
The _three dots_ (`more_vert`) mean "more", so I personally think it works. But since this represents a more important User Menu I'd be OK to try our the _expand_ (`chevron_right`).
