### ISSUE TITLE
'Note' not shown when read only

### ISSUE THREAD

**Issue by srjrol** [directus/app#1432]
# Bug Report

## Steps to Reproduce

1. Create toggle interface
2. Set interface to read only
3. Set a Note to be displayed

## Expected Behavior
Note should be displayed even if the field is read only
## Actual Behavior
Note is not shown when field is 'readonly'
## Other Context & Screenshots
![checkbox](https://user-images.githubusercontent.com/34398302/55242806-fb8dc180-520b-11e9-8285-3201ae056451.gif)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus: 190325A
- Install Method: cloned `master` branch of `directus/directus'

**Comment by rijkvanzanten** [comment]
This seems to happen for all interfaces

**Comment by rijkvanzanten** [comment]
@benhaynes There was an explicit check that would hide the note on `readonly` mode 🤔 

I can't remember why we thought that was a good idea back then 😅  It feels like a bug now!

I'm gonna render the note in both read only and regular modes.

(I think it was because we originally thought of the `note` as `input hints`, which the user wouldn't need in read only mode, cause you didn't have to input anything)

**Comment by benhaynes** [comment]
Weird! Yeah, I agree that we should always show notes. Glad this got found/fixed!
