### ISSUE TITLE
(Soft) Server Error after project change of API Project (missing translation id?)

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1472]
# Bug Report

## Steps to Reproduce

1. Login in as usual to an app admin UI with more than one API Projects
2. Change API Project from admin and login in there
3. "Server Error" is what i see, but it is gone after a normal reload

## Expected Behavior
No error
## Actual Behavior
Error
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/15183757/55890020-e3258b80-5ba9-11e9-9a00-0bc82f3b307a.png)
![image](https://user-images.githubusercontent.com/15183757/55890037-eb7dc680-5ba9-11e9-85aa-565c215aee42.png)

i guess somehow `id` of translations come "too late"

## Technical Details

- Device: [MacBook]
- OS: [eg: MacOS]
- Browser: [Chrome ]
- Directus App: [latest]
- Directus API: latest
- Install Method: [eg: cloned `master` branch of `directus/app`]

**Comment by benhaynes** [comment]
Hey @dev7ch — I was/am getting the same thing. @rijkvanzanten thinks that it is due to the switch from extensions in the API to the App and that it's trying to load them twice. Does that seem right to you? Can you confirm that you are using an App and API that both expect extensions to be in the App?

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/app/issues/1476

(the other one is technically a duplicate, but is way more specific 😁 )
