### ISSUE TITLE
directus_activity table is not cleansed when items and collection are deleted

### ISSUE THREAD

**Issue by srjrol** [directus/app#1512]
# Bug Report

## Steps to Reproduce

1. Create a new collection (food) with field (name). 
2. Add a Food item with name and save it.
3. Delete the item and then the entire collection.
4. Create the same collection and field and a new item with a different name.
5. Notice the Activity history is shown for the new item and the old deleted item.

![food](https://user-images.githubusercontent.com/34398302/56370984-dadcda00-61c1-11e9-8fbe-12e03b0e668b.gif)

## Expected Behavior
Only the new item activity should exist. ```directus_activity``` should be cleansed of related rows when item is deleted.

## Actual Behavior
```directus_activity``` table is not cleansed when item and the collection are deleted.

## Other Context & Screenshots
I notice this does not happen when I simply delete and re-create the only item in a collection.  So it appears to only be a problem when both the item and its collection are both removed.

![image](https://user-images.githubusercontent.com/34398302/56371056-0233a700-61c2-11e9-8de3-89e2ca2d7d3b.png)

![image](https://user-images.githubusercontent.com/34398302/56371052-ff38b680-61c1-11e9-937e-15bf88dd6ed4.png)

## Technical Details
- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Directus: 190325A
- Install Method: Cloned master branch of directus/directus

**Comment by benhaynes** [comment]
First off — nice video! I'm impressed you did all that so fast! :)

So this is tricky. We don't really want to delete activity, even when deleting an item, since that is used for accountability. BUT, but also don't want a deleted item's history to come back to life.

One option (which we've been considering anyway) is to switch the default PK to `uuid` instead of an incrementing integer. This solves the issue with a default config, but not in other situations.

Another option would be to have a soft-delete status on the activity collection. This would allow us to set activity to "deleted" and hide it for subsequent items without actually losing it.

Any others?

Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
> So this is tricky. We don't really want to delete activity, even when deleting an item, since that is used for accountability. BUT, but also don't want a deleted item's history to come back to life.

👍 

I'm all for moving away from auto increment primary keys.

**Comment by benhaynes** [comment]
Yes, let's plan to move the default PK to `uuid` (when we have it ready)... but we still need to make sure that ghost activity doesn't rise from the dead (#easterbuggy) if the user chooses an INT PK.

**Comment by rijkvanzanten** [comment]
I thought the API would use the mysql's auto-increment (that doesn't re-use IDs), so I'm not too sure where this re-used ID is even coming from

**Comment by benhaynes** [comment]
This issue is because we store the activity as `directus_activity.item` (stores PK), then delete the collection and re-add it... the auto-increment resets, but that means it re-uses PKs from before (that might exist in activity). So a _new_ item might show activity from a previously deleted collection item.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
