### ISSUE TITLE
Deleting entries in O2M list deletes the item in the foreign table in addition to the relationship

### ISSUE THREAD

**Issue by justrealmilk** [directus/app#1538]
# Bug Report

## Steps to Reproduce

1. Configure two basic tables and create a O2M interface in one and relate it to the other
2. Create and save entries
3. Delete an entry from the parent

## Expected Behavior

That only the relationship is deleted, not the foreign record as well. If the were to remain the behaviour, adjustments to UI are required.

## Actual Behavior

My precious datas are dust (deleted).

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/156681/56586310-cdd94400-6622-11e9-8a05-505db9175b41.png)

This [ x ] seems innocent and non-destructive. You expect it remove the item from the list, not the database.

## Technical Details

Cloned master branch of directus/directus: c2a534e8e042a7ad1a1757cb7996b2c9fb12c863 (yesterday, April 23)

**Comment by benhaynes** [comment]
@rijkvanzanten — should we add an interface option to choose if the "x" should delete or nullify the value?

**Comment by rijkvanzanten** [comment]
No, I agree with @justrealmilk on this one

> This [ x ] seems innocent and non-destructive. You expect it remove the item from the list, not the database.

**Comment by benhaynes** [comment]
True, but you'll leave the related item "orphaned" with no related pk which also might not be intended behavior. We could include an "are you sure?" confirmation when it's actually deleting it. I mention this because whenever we change these things, someone comes and makes an argument for the opposite way too... so maybe it's good to support both?

**Comment by justrealmilk** [comment]
My personal list of preferences:

1. Orphan the item, remove the relation
2. Add a global setting for intended action (could cause confusion, especially with current users who upgrade)
3. Confirmation modal with [ Orphan the item, remove the relation ], [ Remove from space time continuum (Delete) ]

**Comment by rijkvanzanten** [comment]
@benhaynes I remember us discussing a modal that would ask you what to do with relationships when deleting an item from the top level. Can we re-use that for this somehow?

**Comment by benhaynes** [comment]
I like the modal in principle, but my only problem with it is that it leaves the decision to the _user_ (who may or may not know what they're doing). This would lead to inconsistent deletions with orphans slipping through when they shouldn't, or important data lost.

A Global option seems too broad (since you might have different use cases throughout the project).

I still think the admin should know best, and an interface level toggle for what to do makes the most sense.

**Comment by shealavington** [comment]
_Throwing my opinion in here too..._
I have already clicked that 'X' not expecting it to fully delete the item—but expecting it to 'decouple' from the item I'm currently editing, therefore I would expect an orphan.

I would prefer one of the two below ideas:
1) Show a modal asking if I want to delete the item, or remove the relation (But somehow in understandable terms for someone less knowledgeable)
2) Orphan the item, remove the relation

**Comment by rijkvanzanten** [comment]
> Imo: There's nothing wrong with having some orphan data, you can reselect the item if you changed your mind, however, by fully deleting an item, you can't really go back from that.

I +1 this. The easiest solution in terms of implementation and setup is to make the X in the O2M only delete the relationship.

**Comment by benhaynes** [comment]
OK, I seem to be out-voted here, so let's move forward with orphaned data and/or the modal to choose.

We'll see how long it takes for a ticket to open complaining about the orphaned items. :wink:

**Comment by justrealmilk** [comment]
@benhaynes so salty! I forgot that the product can be used by non-devs and that there are folks who don't know what they're doing... An admin only toggle would be cool, but if one of the options is that it deletes the foreign item immediately... That freaks me out.

Imagine a scenario where you've curated two collections of data and you start relating them to one another and you erroneously attach the wrong ones. How do you unrelate them without deleting one?

**Comment by benhaynes** [comment]
Haha, maybe it's just because I've been working on Directus for so long and seen so many use-cases that I want to keep as much flexibility as possible.

> if one of the options is that it deletes the foreign item immediately... That freaks me out

There are a lot of non-technical folks on the App side that we should be thinking of. Personally, giving the _user_ the option to decide if something is deleted or un-linked seems much more risky/stressful to me... and that decision needs to be made every time the X is clicked.

However the "Interface Option" could be given the "safer" default (unlink) and could have plenty of big red warnings to make sure the admin knows what they are doing. This is a one-time decision based on how precious the data is.

I totally get the "we don't want to accidentally delete the related item" argument — but there is a strong argument for "this is meaningless relational data that we don't want orphaned and swept under the rug". If we want to maintain that ability then we need to have this option _somewhere_.

And lastly, just so I've made a reasonably compelling argument for why we might want to _delete_ relational items:

Imagine we have a "carousel" field where you create simple slides of text (quotes, paragraphs, etc). The related items in this example are pretty meaningless and disposable. You might quickly create 10-15 on the parent item, re-arrange a few, delete a few more. The intention is never to go searching for an existing one (in fact, "Choose Existing" would be turned off and the related collection would be hidden from the main nav). So all those items getting deleted just pile up and require some annoying manual garbage collection.

Food for thought! 😄
