### ISSUE TITLE
Fields without interface fails to load field name.

### ISSUE THREAD

**Issue by shealavington** [directus/app#1542]
# Bug Report

## Steps to Reproduce

Create a field without an interface (outside directus)
Try to edit an item,
you won't know what field you're editing.

## Expected Behavior

Display column name above field input.

## Actual Behavior

Not displaying anything above field input. (Venueadd1)

## Other Context & Screenshots

Setup Area:
![Selection_061](https://user-images.githubusercontent.com/16869302/56646315-3c47f180-6677-11e9-9cc3-2c281039df13.png)

Edit Screen:
![Selection_060](https://user-images.githubusercontent.com/16869302/56646306-3a7e2e00-6677-11e9-81e6-d7fd04fe58f8.png)

## Technical Details

- Directus App: 7.0.3

**Comment by benhaynes** [comment]
I assume this is because there is no record in `directus_fields` — but Directus should use the "title formatter" to show a label based on the database column name.

Although we _are_ saying that Directus should function as a database admin tool, and mirror the database... I'll label this as an enhancement.

**Comment by shealavington** [comment]
Agreed—that's likely the reason why it's not working. And that is the expected behaviour.
I labelled it as a 'bug', as it was working before, however, after a `git pull origin`, it's stopped loading the titles.

**Comment by nstCactus** [comment]
Seems to be fixed in the master (2fd7bca7f7bc7a6e6b848fd804990c37d05cecb0).

I created a `temporaire` column in my `ventes` table. I went to `/collections/ventes/1` and didn't find the new column. I then went to `/settings/collections/ventes` and found this :
<img width="901" alt="Screenshot showing the new column is present in the settings" src="https://user-images.githubusercontent.com/353843/58201055-763b0080-7cd4-11e9-95dd-20a6364183a6.png">

If I click the `Manage` button of the new field and go back to `/collections/ventes/1`, the new field is present & editable.

**Comment by rijkvanzanten** [comment]
You used to be able to edit these fields without making them 'managed' first. I believe you're right in saying that that change might've fixed this issue too @nstCactus.

Btw, thanks for all the contributions! Means a lot ❤️

**Comment by rijkvanzanten** [comment]
@shealavington Could you confirm this is still happening for you?

**Comment by shealavington** [comment]
Tested, your fix, fixed it. :smile:
