### ISSUE TITLE
Image background

### ISSUE THREAD

**Issue by shealavington** [directus/app#1545]
# Bug (Enhancement) Report

## Steps to Reproduce

A single image should have a background otherwise it looks odd.
The image seems to have a white background overwriting the parent with the correct background.

## Expected Behavior
![Selection_066](https://user-images.githubusercontent.com/16869302/56647443-5da9dd00-6679-11e9-8d9f-022530624ff9.png)

## Actual Behavior
![Selection_065](https://user-images.githubusercontent.com/16869302/56647451-626e9100-6679-11e9-951e-b36740f5d442.png)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch of `directus/directus`]

**Comment by benhaynes** [comment]
Yeah, this was caused by fixing another issue. The `img` white background fixed an anti-aliasing issue with the rounded corners of the `card` component. I let this slide because I thought we were also overhauling the `file` + `file preview` interfaces but those didn't get done yet.

Ideally I'd like to not use the stretched card component for the `file` interface, instead having something more like the `file preview` view (bigger).
