### ISSUE TITLE
Directus PWA [Idea]

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1566]
As far as I have seen, there was the idea of introducing a pwa feature to Directus, but canceled due to whatever reason. #391

First of all, the reason why I think it would be nice to have is that it allows people to access Directus even easier than before, sure you can create a shortcut to a website on mobile, but I think nobody has done this ever before and standard directus users wont even know that this is possible.

Second, it may sound crazy in general, why should you be able to access Directus ofline when the whole idea of a CMS is that it is online but I think that is the wrong way to view it. When talking and thinking about a PWA, you mostlikely expect: "Ah, that thing that allows you to see things offline" and I would say in this case, we should think differend.

For example, why did twitter bothered to create a PWA for their service, when there is already an app on Android and IOS and using it offline would not make that much sense? Because it reaches to more people and makes it more accessable to them. And this is the same case for Directus. When you're working with Directus (as a content creator / blogger or such), its much easier to klick on an icon on your screen than going into a browser and typing in the url of the app.

I'm interested in what you think and would like to start a little discussion about serving directus as a PWA.

**Comment by shealavington** [comment]
It's definitely a welcomed idea, however, it's a lot of work and you need to ensure it's done right which would be very difficult considering the idea behind directus managing data. 
* Data change requests when offline would need to be held until online
* Would need a status to say things have changed but not been uploaded yet.
* Need a way to clear the cache/invalidate worker when updates happen.
* Caching can't be too forceful otherwise you might not see changes made by others.
* — Lots of other things I can't think of right now haha.

Added Note: I just quickly read the issue you linked and yeah, as Rijk mentioned, the main issues seem to be: Difficult to invalidate the old cache/service worker when a new release happens, and as Directus manages data, it doesn't make sense in some cases to have that as a PWA.

**Comment by Nitwel** [comment]
Yes, implementing a service worker who does all this stuff would be difficult but why should the directus PWA app be capable of doing this right from the beginning? I would say it would be enough to implement a PWA in the simplest form and disable all functionallity that needs an online connection. So when you're offline you can view directus but dont do much else with it. The main reason why I think a PWA would be nice to have isn't about the factor of doing things offline anyway as explained above, its more about the accessability that you can easily open it.

Sure, later when there is more time to do features we could think of adding your points ontop of it but for now, it would be enough to just cache data offline and disable all buttons that need an online connection / have them enabled when there is one. 

And PWA in general are getting more features each month. Maybe offline caching updates to the db is much easier today already or in a few months, who knows.

**Comment by shealavington** [comment]
It sounds like, what you're after, is an app-button to be shown on pwa-enabled devices for accessability.. right? With that, you should be able to "add-to-homescreen" and have the button show already :P 

I feel like you're missing the main issues with making Directus a PWA though, haha...
* Directus isn't really an offline-usable PWA to begin with.
* We won't be caching any records client side, seeing that data needs to be up to date. 
* We can't  consistently invalidate the service worker on new releases _(yet)_
* We don't need a service worker to cache just the static files, if we already have the regular browser caching.

**Comment by Nitwel** [comment]
> First of all, the reason why I think it would be nice to have is that it allows people to access Directus even easier than before, sure you can create a shortcut to a website on mobile, but I think nobody has done this ever before and standard directus users wont even know that this is possible.

^^

**Comment by rijkvanzanten** [comment]
> The main reason why I think a PWA would be nice to have isn't about the factor of doing things offline anyway as explained above, its more about the accessability that you can easily open it.

It already does this :) Directus has a webmanifest file that makes all of this look pretty on mobile installs: https://directus.app/manifest.webmanifest

The reason why I stopped working on the service worker implementation is mostly because of the reasons listed above. Directus doesn't fetch all the data, so being able to view your data offline would result in an outdated subset of your data, which is most likely not going to be an accurate representation of your data. I'm also not too sure what implications this might have for the user, as it's not very common to be able to use an app you're required to login to without having internet connection. The second big problem is authentication. If you're offline, how do we know you're user is still allowed to view all this data? For caching static files, the browser itself already provides what we need.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Nitwel** [comment]
We could also close this one completly.
