### ISSUE TITLE
Settings: Field Layout

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1586]
# Feature Request
![image](https://user-images.githubusercontent.com/8030134/57201328-19e49b00-6fca-11e9-9116-649695022687.png)

## What problem does this feature solve?
It can quickly layout the page

**Comment by benhaynes** [comment]
Love it! Thanks @cdwmhcc ... here is my take (applying the new design system). I was thinking we could keep a toggle to switch between the editors (though @rijkvanzanten will say let's just use the layout mode and keep things simple 😉). Since the width is easily visible by looking at the layout, we can remove that dedicated dropdown and use the contextual menu (three dots on right) instead:

```
Half Width
Half Width + Gap
Full Width
Fill Width
--------
Edit Field
Duplicate Field
Delete Field
```

![Directus 8 – Settings Alt](https://user-images.githubusercontent.com/522079/57233574-e49d7480-6fec-11e9-924c-d6bf95a62d9a.png)

![Directus 8 – Settings](https://user-images.githubusercontent.com/522079/57233580-e7986500-6fec-11e9-9ce9-7c69fcd265a7.png)

**Comment by benhaynes** [comment]
Ref (and possible duplicate?): https://github.com/directus/app/issues/759

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/57238061-1baa6f00-705b-11e9-9e08-b12ab1955f77.png)

This should use `hover` instead of `Click`

**Comment by cdwmhcc** [comment]
> Ref (and possible duplicate?): #759

![image](https://user-images.githubusercontent.com/8030134/57238061-1baa6f00-705b-11e9-9e08-b12ab1955f77.png)

This should use `hover` instead of `Click`

**Comment by cdwmhcc** [comment]
> Love it! Thanks @cdwmhcc ... here is my take (applying the new design system). I was thinking we could keep a toggle to switch between the editors (though @rijkvanzanten will say let's just use the layout mode and keep things simple 😉). Since the width is easily visible by looking at the layout, we can remove that dedicated dropdown and use the contextual menu (three dots on right) instead:
> 
> ```
> Half Width
> Half Width + Gap
> Full Width
> Fill Width
> --------
> Edit Field
> Duplicate Field
> Delete Field
> ```
> 
> ![Directus 8 – Settings Alt](https://user-images.githubusercontent.com/522079/57233574-e49d7480-6fec-11e9-924c-d6bf95a62d9a.png)
> 
> ![Directus 8 – Settings](https://user-images.githubusercontent.com/522079/57233580-e7986500-6fec-11e9-9ce9-7c69fcd265a7.png)

Is this the new UI?
It's pretty.

**Comment by benhaynes** [comment]
Yeah, the new UI (partially implemented already). 😄

**Comment by herrbomm** [comment]
When will this "new UI" be released? Any roadmap i can look into? 😛

**Comment by benhaynes** [comment]
This one's too small to be on our roadmap (which only outlines larger updates), but our team's resourcing increased as of today, so we should be able to get this implemented in the next few weeks... unless a PR comes in first. ;)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
