### ISSUE TITLE
Simplify translations

### ISSUE THREAD

**Issue by henrikwirth** [directus/app#1629]
# Feature Request

As of now, the translation works very flexibel over the translation interface. The only problem is, that it is a very tedious process and allows many mistakes, if setup incorrectly. 

## How do you think this should be implemented?
So my thought was, to integrate translations more into the core, by, for example, adding a `directus_languages` table, that holds all languages. Then there could be an area in the Project Settings, where you can define the used languages.

Maybe you could make it even possible, to define all the collections, that should be translated and also define their translated fields in this settings. 

While this might simplify the use of translations a lot, this would also make the setup less flexibel. Therefore it should be optional, to use the global settings.

How exactly this could be solved in an elegant and 100% customizable way, I leave open for discussion.

## What problem does this feature solve?
Adds simplicity ... keeps ability to customize

## Would you be willing to work on this?
Yep, bring it on.

**Comment by henrikwirth** [comment]
Oh, and to make this even more of a feature. How about adding some sort of Overview, that can show you if translations are missing. You could predefine what fields in a collection should be absolutely translated and then you could filter by `missing translations` and `critical missing translations` (some better naming). That would be very powerful for people who write lots of text, that needs to be translated.

**Comment by rijkvanzanten** [comment]
> So my thought was, to integrate translations more into the core, by, for example, adding a directus_languages table, that holds all languages

If it's holding all languages which don't change, it could also be a static file

**Comment by henrikwirth** [comment]
> If it's holding all languages which don't change, it could also be a static file
Ah you mean as suggestion to select what languages are used?

**Comment by rijkvanzanten** [comment]
Maybe I'm mistaken what this directus_translations table would do. I thought it would hold the languages?

| code | name     |
|------|---------|
| en     | English  |
| de     | German |

**Comment by henrikwirth** [comment]
> Maybe I'm mistaken what this directus_translations table would do. I thought it would hold the languages?

Nope, thats what i meant in the first place :D. But why writing it in a static file? Wouldn't that make it more inaccessible again?

**Comment by rijkvanzanten** [comment]
> Nope, thats what i meant in the first place :D

Wait.. so you did mean that or not? I'm confused 😅 

> But why writing it in a static file

If we have a lookup dictionary that doesn't ever change and doesn't hold user generated content, we might as well put it in a static file

**Comment by henrikwirth** [comment]
Fair enough, we have the config file, which could hold this information. 
Alright lets rethink this a little (without customizable consideration). An obvious workflow for me would be to:

1. Somewhere define the languages I want to use (config or db_table/settings)
2. Define `in a collection`, if it should be translatable
3. Define `in the fields`, if they should be translatable
4. Creating/Editing an Item gives me the option to switch between languages to edit
   - Could be some flags somewhere at the top, or simply a dropdown if one uses a lot languages (make it configurable)
   - The user can set in his profile which language he would see/edit preferably and then gets this language shown first. So if a translator wants to only translate his language for example.
   - When switching to another language, replace the fields with only the ones, that are translatable (you could just reuse the old fields and get there values field and hide the fields that are not translatable, what ever seems better for performance and data integrity)
5. Have an Overview Page, to see what translations are missing. Could be also with statistics etc.

I am not too sure how we could make this, so it would not be a `have to` feature, but maybe you @rijkvanzanten know of a way to decouple it?

**Comment by benhaynes** [comment]
Here are my thoughts on languages:

1. We could have a `directus_languages` collection that could be used globally. This could have all languages in it (and you could always add more in the DB)... but also a `status` field that is used to turn on/off which languages are used. The only downside here is that this would be global (for all translations in the instance). I like this because it's how translations work now so it should be pretty easy to make work (just using a default collection for languages that can be overridden, and adding support for `status`).
2. We could have a full list of languages in a static file (with codes and labels) and you choose which ones you want to use within the translations interface options. This has the benefit of allowing different languages per interface... but would be a little harder to add custom languages to. But, you could always use a custom collection (the way we do now) if you need something more custom.

So that should help with the confusion and extra work of setting up languages... then we need an easier way to setup the fields in the relational collection (the actual translations). Again, I see two options:

1. We could keep things how they are now, saving all translations as relational data in a special O2M. To make setup easier we could have some helpers when adding a translations field. I think it'll be more confusing to open a new modal for the relational fields, but maybe we can brainstorm this. We could also add a dedicated `translations` tab in the new field modal (similar to how we have a conditional "relations" tab). Since i18n is so important, I would be open to this.
2. Another direction is to have a non-relational option... where translations are saved in JSON. The problem here is that this isn't really how Directus works now. So it might not be very clean to setup `required`, `defaults`, `interfaces`, etc... since right now this is all tied to `directus_fields`.

Lastly, we can use `required` for critical translations... and the interface itself can show a count/list of how many non-critical translations are missing.

**Comment by FRSgit** [comment]
Just a small note: if you would go for static file then you can think of using some external tool to simplify translation process (and to help you with maintaining current translations). I know at least 2 tools like this which have github apps and integrations: crowdin and poeditor (see in github marketplace).

**Comment by benhaynes** [comment]
Thanks @FRSgit — this ticket is actually about user translated content (not the Directus App translations). For the latter we actually have a different feature request: https://github.com/directus/app/issues/793

Good idea either way! :)

**Comment by FRSgit** [comment]
Ah, sure, sorry for offtop, working at night has it's downsides, cheers! ;)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
