### ISSUE TITLE
O2M doesn't set sort value on adding new item

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#1689]
It only sets the sort value when manually sorting the values.

Ref #1670

**Comment by rijkvanzanten** [comment]
@ThomasKliszowski you can sort the O2M interface by any field. What should happen when you have the interface sorted by let's say 'title' and then add a new item? Should it still set the sort field based on the newest item gets the highest sort value?

**Comment by ThomasKliszowski** [comment]
I know what you are talking about.
I faced the same issue when trying to work on #1500.

I guess we only have 2 options in this case:
- disable the _sort by any field_ feature if we have a `sort` type field.
- always put the newest item at the end of the list, with the `highest value + 1`, the option you talk about

Maybe the second one is the best option, since we can keep the _sort by any field_ feature.

**Comment by benhaynes** [comment]
Definitely the second option. :)

We want to keep the ability to sort by other fields, but that is a temporary view so we should always base the sort value of _new items_ on `max(sort) + 1`.

**Comment by rijkvanzanten** [comment]
This is fixed in https://github.com/directus/app/pull/1677
