### ISSUE TITLE
Field extensions do not load when using history routing mode

### ISSUE THREAD

**Issue by gridsystem** [directus/app#1748]
I believe there is a problem with the included .htaccess which routes js and css to the default index.html. You can recreate this problem by switching to history mode in the config, and navigating to a page containing fields.

<img width="1522" alt="Screenshot 2019-06-12 at 4 59 56 pm" src="https://user-images.githubusercontent.com/2365737/59367190-870aef00-8d33-11e9-96a2-d2cb1dbe3474.png">

Inspecting the requests shows that index.html was loaded in place of the expected css or js.

<img width="358" alt="Screenshot 2019-06-11 at 9 46 23 pm" src="https://user-images.githubusercontent.com/2365737/59367125-6773c680-8d33-11e9-9c90-b7e0c33938c0.png">

Switching back to hash routing fixes the issue.

Unfortunately I'm not confident enough with apache configs to submit a PR.

**Comment by rijkvanzanten** [comment]
We can't fix this. These lazy loaded paths are automatically made into absolute URLs by Webpack, which in turn breaks the loading of the interfaces cause the path needs to be relative.

The only real way to fix it would be to provide two different builds for the app, one with relative url support (eg `/admin/index.html`) and one that always lives in the root `/`. This doesn't really solve it fully either, because not everyone who uses history mode wants to have the app in the root level of the domain. 

Seeing that this adds a massive overhead for a feature that doesn't necessarily add any useful features, I'm gonna play [the 80/20 card](https://docs.directus.io/getting-started/contributing.html#_80-20-rule) and consider this not worth it.

**Comment by rijkvanzanten** [comment]
We'll remove support for history mode in the upcoming version. Ref https://github.com/directus/app/issues/1759

**Comment by gridsystem** [comment]
Do you think it's worth adding a line to the docs explaining how to build the vue app from scratch with history mode enabled?

**Comment by rijkvanzanten** [comment]
I'm not sure about that.. If we put it in the docs, we endorse building the application from source, which we don't. I would also require changing some of the buildchain config, basically requiring the user to keep a fork of the application
