### ISSUE TITLE
Visual glitch when removing filters

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1766]
The ticket below got transferred to the API, but there is also an App issue:

> There is a style artifact when a search doesn't have a result and you clear the filter the table view wildly jumps from bottom to top of the page ( I checked using latest chrome and firefox )
@24js

https://www.loom.com/share/9c6761cbd37548bd82045b37ed54747f

Ref: https://github.com/directus/api/issues/1025

**Comment by theharshin** [comment]
This is due to the table, which is jumping from bottom to top as the error hides. Error component has an exit animation which takes few milliseconds to hide meanwhile the table comes in as the loading stops. @rijkvanzanten Should we remove the exit animation? I can't think of any alternative. We may use absolute positioning of error blocks but that would be a messy!

**Comment by benhaynes** [comment]
I'll leave this question for @rijkvanzanten. I'm fine removing the exit animation, but maybe there's another solution?

**Comment by rijkvanzanten** [comment]
Yeah lets kill the animation for now. I don't think having it is worth the absolute / fixed position hacks

**Comment by theharshin** [comment]
Fixed in https://github.com/directus/app/pull/2023
