### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by dargains** [directus/app#1824]
Hi there.

I somehow can't upload images to the app once it goes online. I've tried locally (on my computer, using wamp) and it works fine. I keep getting an error with the following message: "PHP File Information extension was not loaded."

I've looked through the docs but can't find anything related to it. Is some config missing?

Directus version: 7.6.1
PHP version: 7.2

Thanks in advance!

![image](https://user-images.githubusercontent.com/16159324/60772463-c3412d80-a0ee-11e9-9843-f0d44e88a941.png)

**Comment by AstralProgrammer** [comment]
Hi @dargains,
have you checked the available PHP modules on your local vs the server your online application is running on? Also, check the logs for more details on the error.

**Comment by shealavington** [comment]
I'm going to close this due to user misconfiguration, as the error states, you're missing the PHP extension 
 `File Information` also known as `fileinfo` on the server you're using.

You may find something useful in this search to help you enable that extension:
https://www.google.com/search?q=php+enable+"fileinfo"

Please ensure you've met all of the Directus requirements: 
https://docs.directus.io/advanced/requirements.html#php-extensions
