### ISSUE TITLE
Second level translated fields are stored but not rendered back on read

### ISSUE THREAD

**Issue by chintohere** [directus/app#1849]
### Versions 
App: 7.6.2
Api: 2.2.1

### How to  reproduce
Create collection structure with second level translated fields in directus.

[schema diagram](https://dbdiagram.io/d/5d2c4d6bced98361d6dca889)

1. Create new article
2. Add new section
3. Add translated value *section_name*
4. Save. Observe that save is successful
5. Read the article again. Notice that the translated fields are empty

**Comment by oliverpool** [comment]
We are also affected by this bug.

Looking at the Network requests, it appears that the data as been saved (is present in the response under the `translations` object).

I have some coding knowledge and I am going to dig further (I guess the issue is in the `Translation` component, since the API response looks fine).
