### ISSUE TITLE
Status Mapping: Repeater Broken

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1864]
When updating the Status Mapping in a `status` field's options, adding a new item seems to remove an existing one.

**Comment by theharshin** [comment]
![image](https://user-images.githubusercontent.com/7118937/62041627-ba3d0b00-b219-11e9-83c9-ca43896cf8e8.png)

The issue seems to be with an option "Index: used as key" option in Repeater field Options.
The `status` setup uses this option and a `value` is used as key and this in a case where value starts with same text, it may override previous one.

@benhaynes Can you confirm this is the only case when it happens? I can reproduce this issue only in this case.

**Comment by JbalTero** [comment]
@benhaynes @bjgajjar This also happened to me: using the latest develop branch of app

https://drive.google.com/file/d/1cOSPiuxZ4d0Xhf4yz41_gM_4zpGdBT2n/view?usp=sharing

**Comment by benhaynes** [comment]
Thanks @JbalTero — it's high priority, so it'll be next on our bug fixes... but we're still wrapping up the new Auth Flow for another few days. We'd love any help getting a PR... otherwise we should get to it in the next week or two.
