### ISSUE TITLE
Input field type of Dropdown / Options / Choices

### ISSUE THREAD

**Issue by morrenke** [directus/app#2083]
Is there a way to change input field type of Choices when I should set the options for a dropdown interface? I would like to add json instead of typing manually. Please check the pictures below:
![dropdown_json](https://user-images.githubusercontent.com/23039613/65247950-a7480800-daf1-11e9-972f-ca21b6fd84bc.png)
![dropdown_manual](https://user-images.githubusercontent.com/23039613/65247952-aa42f880-daf1-11e9-9f65-dd0ad41f02ee.png)

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I don't know. It boils down to personal preference. I think setting up the options for a dropdown in a repeater interface is a better UX for 80% of the users. Adding support for "choose your own interface" per option might be a bit overkill in this case

**Comment by benhaynes** [comment]
I think it would be nice if the `repeater` interface itself had an option (`allow_editing_source`) that toggled a button for switching between the current UI and a raw JSON editor. Similar to how our markdown lets you go between raw and formatted. This would let advanced users copy/paste/edit values more efficiently... and since it's an interface option it could be turned off as needed.

To me, _that's_ what this feature request should be... not choosing interfaces (more high-level).

**Comment by morrenke** [comment]
Yes, exactly! It would be convenient for both 80% and advanced users as
well. (I've found a workaround, fixed the issue with Postman patch request,
but a toggle would be really nice!)
Thank you for thinking about it!
Dorka

**Comment by rijkvanzanten** [comment]
> I think it would be nice if the repeater interface itself had an option (allow_editing_source) that toggled a button for switching between the current UI and a raw JSON editor.

There's no end to that though. You can extend that to "I wish the checkboxes interface would let me enter the raw JSON array", or "I wish the translations interface would allow me to edit the JSON directly"....

**Comment by benhaynes** [comment]
Correct — with no one in control of the software there would be no end.

That's why I/we are here... to make sure a balance is struck. We can both agree editing raw checkbox values is dumb, disagree on the repeater, and both agree that WYSIWYG should have a raw toggle.

So clearly it's about a balance... and this option in no way sets a global precedent that we have to add similar options all over the place.

**Comment by benhaynes** [comment]
Rijk and I are discussing this offline (Community Slack)... but here are a few things we came up with:

What if a user (with no DB access) creates a complex status, and wants to use it across all collections. It's so nice to just paste it in instead of manually setting up 20 the exact same.

What if you just want to see a birds eye view of status (or a user field that's even more complex)? The repeater only allows ONE to be open at a time, so it's a way to see all values at once.

We'll keep discussing... but are too busy with bugs and v8 at the moment to take this one now anyway.
