### ISSUE TITLE
Soft deleted items causes problem when one of its field is "uniqe"

### ISSUE THREAD

**Issue by anelad** [directus/app#2085]
Let's say we have posts collection, having a "unique" slug. Then let's say user soft-deleted one. Now, if the user tries to add a new item with the same slug of the soft-deleted one, it will be rejected by the database since the field is "unique".

I think with this bug; usage of the draft approach as I proposed at #2072 extended with soft-delete is inevitable.

**Comment by anelad** [comment]
The temporary solution is disabling soft-delete of course.

**Comment by benhaynes** [comment]
As you said, this is relatively unavoidable with a _normal_ workflow. Directus stores draft items in the same table, but flagged with a different status. That means the database will choke on the duplicates for unique fields. Some other options would be:

1. Save soft deleted items to a separate "mirrored" table using hooks.
2. Save soft-deleted items to the `directus_revisions` table. This is similar to the idea for draft edits: https://github.com/directus/app/issues/762
3. Remove the database unique flag and make it "software only", so that Directus can ensure things are unique for published items only. (this goes against the "database mirroring" of Directus).

Again, this is just how databases work, so I'm not really seeing this as a bug, per se. I'll save it as an enhancement and we can continue to discuss how best to support things like this.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by renatocron** [comment]
This could be solved using another column to mark if an item is active with null, and when deleted set to 1, and then create a unique index on that column.

It is still a new field, it's the 'best' what you can do without partial/conditional unique constraint.
