### ISSUE TITLE
config.js API name should be a param within Global Settings

### ISSUE THREAD

**Issue by gianniskarmas** [directus/app#2103]
Whenever I update by pulling updates from the github repo the API variable inside /public/admin/config.js gets overwritten.
It should be a parameter within Global settings or take its name from the Project Name.

**Comment by rijkvanzanten** [comment]
We're including config.js in order to make the admin work right away in the combined suite.

The app can't pull this config from global settings, as it's using this exact config to know what API to use in the first place. You could consider using the app standalone (which doesn't include the config file on releases) or backup your custom config on updates.
