### ISSUE TITLE
Code Interface — save as array error

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2171]
When trying to save a value from the `code` interface, I'm getting the following error:

"Attempting to write an array as the value for field "code" in "interface_library""

Here is the value I tried to save:

```
{
    "test": true
}
```

**Comment by bjgajjar** [comment]
Hey @benhaynes  - It seems like you are trying to store `JSON` for `string` type.

`code` interface is supporting 2 datatypes.
- string (Supports with `Plain Text` language)
- JSON (Supports with `JSON` language)

It is already working. But the issue was - the default datatype is `string` and the default language (Options) is `JSON`. Can you please verify the `Language` and `Datatype` at your end?

I update the default `Language` appropriate with `Datatype` in https://github.com/directus/app/pull/2195.
