### ISSUE TITLE
Compound sorting

### ISSUE THREAD

**Issue by dur41d** [directus/app#2267]
Currently the app only allows sorting with one field. It's a good idea to allow sorting by multiple fields. For example, I have a collection of articles that I would like to sort using `sort=sort,-id` so that I always have the latest article on top and allow manual sorting. 

I modified the `directus_collection_presets` table `view_query` value to be `{"tabular":{"fields":"title,section,author","sort":"sort,-id"}}` but it didn't work. It will be good to support this scenario.

**Comment by rijkvanzanten** [comment]
I'm not entirely following what you're trying to achieve. The `sort` column holds an integer that's incremented (1, 2, 3, 4, 5, etc), so sorting by more than 1 field won't do anything. Sorting by two columns only makes sense if the first column has duplicates, lets say 1, 1, 1, 1, 2, 2, 3, 4, 4, 5.

I'm also not sure how we would support this from a UX perspective. Clicking a column makes sense to sort by that column, but now we'd allow clicking on multiple columns to sort by multiple columns at a time?

**Comment by dur41d** [comment]
The sort column value is null by default for a new entry which makes it go to the bottom of the list.

**Comment by benhaynes** [comment]
I wonder if this will pass our 80/20 rule. I agree it would be a great power-user feature... but might not warrant the extra code/UI complexity. But let's keep discussing... maybe there's a good way to get this in.

Also, worth mentioning that you can choose if `null` goes to the end or beginning with the `sort_null_last` global setting.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dur41d** [comment]
@benhaynes sort_null_last global setting solution sounds interesting and I want to try it. I couldn't find how to set it. Do you know how?

**Comment by benhaynes** [comment]
It's within the Global Settings in the App

**Comment by dur41d** [comment]
Manual sort is really not working for me since I want the most recent entries to show up on top. I did disable sort_null_last option which means that new entries with sort value null will show up on top. However when you add another new item it will be second. I think the manual sort function has to be re-thought. I don't new entries can be null but they should always have a value which is equal to the id value by default unless the sort order is changed by the user. 

# Steps to reproduce

1. Disable sort_null_last option in global setting so that new entries show on top.
1. Create a collection with sort column.
1. Add few entries. The sort value will be null.
1. Enable manual sort and sort few rows. The sort column will now be filled with values according to the sort order (BTW this is a performance problem for large collections).
1. add a new entry. it will show up on top.
1. add another new entry. it will show up second and I want it to show up first so that the most recent article is on top.

Here is a design suggest for the manual sort. 

1. On insert the value of the sort should be equal to the id. 
2. When the user manually re-sorts an entry the sort value is exchanged between the entry and the one before it. 

I think this design is simple and performs very well and produces the most intuitive user experience. The semantics have to change as having a higher sort value  will mean showing up on top unlike the current behavior.

**Comment by rijkvanzanten** [comment]
> 1. On insert the value of the sort should be equal to the id.

The primary key doesn't necessarily have to be an auto-incrementing ID so that might not apply. Also, an auto-increment doesn't take deleted items into account, so it's very easy to end up with gaps in the sort order.

> 2 When the user manually re-sorts an entry the sort value is exchanged between the entry and the one before it.

That's basically how it works now.
If you move item with sort 32 to slot 25, every row with sort 25 through 31 gets bumped up 1 to maintain the sort order.

**Comment by benhaynes** [comment]
Also, most things in Directus are meant to be a "starting point"... and extensible by design. So while our current sorting may work for 80%+ of users, others can use event hooks or custom extensions for their own use cases.

For example, you could use event hooks to set custom sort values for new/updated items in any way your project needs — avoiding sort `NULL`s altogether.

**Comment by dur41d** [comment]
gaps in the sort order mean nothing as long as the items sort correctly and this is what feature is 'manual sort'. Maintaining a gapless sort order serves no value.

I disagree that the current behavior works for 80% . My use case is for a simple blog which is more than 80% of the cases.

**Comment by benhaynes** [comment]
This will quickly turn subjective, but our agency has built over a hundred blogs — and close to 90% of them rely on a `publish_date` `DESC` sort. I can't recall any that were manually sorted. Again, this is all based on individual needs.

Long story short, we'll happily review any PRs for this feature... but for the foreseeable we'll be focused on bug fixes. In the meantime, we'll let the community vote (👍👎) on this ticket to gauge interest.

**Comment by dur41d** [comment]
That does not mean that manual sort is working. It means that it is not being used. However, if it's needed then it does not work for a blog scenario.

**Comment by benhaynes** [comment]
Blog example aside, the sorting works well for what it is within the constraints of our platform's goals. It is a simple and optional way to drag a small number of items (doesn't work across pagination or large data sets) to a new order from the browse/layout page and set or swap an INT value. That's it. Anything more complex and we have to start making assumptions about how users are organizing/storing their data... so that will all be left to custom code/hooks/extensions.

We can't make broader/global assumptions about user architecture/data, so we can't assume that you're using an auto-increment `INT` primary key, since users may want to use a `STRING` PK, and then your recommended solution no longer works.

We could potentially add an interface option to the `sort` interface that lets you choose how the initial data is calculated... but that would need to be discussed on the appropriate ticket. Speaking of, I was under the impression that this ticket was requesting compound **ORDERing** within the App listings. If you're requesting a new **SORTing** feature, that should be a separate ticket.

**Comment by dur41d** [comment]
I don't want get into big argument and win/lose situation. In my view, a blog use-case represents the majority of any CMS use-cases. The current implementation of manual sort does not support it. I suggest that you fix it instead of defending the current implementation. 

I used compound sorting to solve this issue and that's why we're having the discussion here. I'm just trying to use your system and to find solutions for the problems i'm having which are real problems.

What do you suggest that I use to enable the user to control which article appears first in a blog?

**Comment by dur41d** [comment]
The solution I suggested is for the default implementation of a directus collection which uses an auto incremented id. The auto increment is detail so please don't focus on it. The idea is that the sort value is not null and is larger than the one before it. The auto increment is just a simple way to achieve that. It's possible to do that in the API code and not rely on the database to generate the value. However, in my view, relying on auto inclement is good enough for a 'default' implementation.

**Comment by benhaynes** [comment]
As I mentioned, we sort by a `publish_date` field `DESC` for articles. To surface priority content, we've used `boolean` toggles or separate M2M fields to track ordered subsets to be displayed first.

> I suggest that you fix it instead of defending the current implementation.

I find this statement presumptuous and inconsiderate. You're allowed to have an opinion, but not to imply this feature is fundamentally broken because it doesn't fit your use-case. You can't assume everyone builds blogs the same way you do. Again, until your feature request is approved, just add auto-increment to the sort field in your database.

In any event, I'm closing these comments as _off topic_. Any subsequent SORT comments should be on your original Feature Request: https://github.com/directus/app/issues/1262
