### ISSUE TITLE
Highlight current table in edit mode

### ISSUE THREAD

**Issue by benhaynes** [directus/app#235]
When on the Edit Detail page, it should still highlight the nav sidebar table/collection you are in.

**Comment by rijkvanzanten** [comment]
Because I changed it to use `router-link-exact-active` instead of `router-link-active`, it now only renders the link blue on the exact page, and not the nested edit views. 

Make sure to write an exception for the user profile / user directory section in the user menu, so we don't end up with two blue links in the user menu
