### ISSUE TITLE
`published_on` Datetime Field

### ISSUE THREAD

**Issue by jacobrienstra** [directus/app#2409]
Like created_on and modified_on, in that it is automatically set, but only when the status is changed to published (or, any given status, I suppose, since published isn't forced)

There may be a way to do this by looking at the activity table, I suppose, but it'd be nice to have it as a first class field. 

Reason for this field is that you may have a draft article sitting around for a long time before its published, and therefore the created_on field would be wrong, and after publishing you may have to go in and fix things without changing the modified date.

Essentially a conditional datetime field. So file this under conditional field, but if other people would find this useful as already set up, could be a nice out of the box field, uneditable like created or modified.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
So we have two things here: the `status` field, and the `published_on` field (type)... and they should be intuitively interrelated as much as possible. I'm not sure if this is a conditional, or if they are more connected. Let's cover some examples:

### Example 1
* `status` is **"published"**
* `published_on` is in the **future**

This **should NOT be returned** because the published on date has not happened yet.

### Example 2
* `status` is **"published"**
* `published_on` is in the **past**

This **should be returned** because the published on date has not happened yet.

### Example 3
* `status` is **"draft"**
* `published_on` is in the **future**

This **should NOT be returned** because the published on date has not happened yet and it is draft.

### Example 4
* `status` is **"draft"**
* `published_on` is in the **past**

Should this be shown? This is a AND/OR argument — here are the options (perhaps this could be an interface option for the status/published date fields?):

1. This is in draft mode because the user doesn't want it published yet (regardless of the publish date), and so no matter what, this is not returned as published.
2. This is set to draft mode _because_ the publish date hasn't happened yet. The thinking here is that the status _reflects_ the current state... and once the published date has passed, the item _becomes_ published. The reason I like this is because if you look at items in the App (listing or detail) you will see the appropriate status (eg: the colored dot) based on the status date too. 

But the problem with direction 2 is that without a server cron job (or some interval task service), we can't auto-update the status as soon as that date passes the threshold. BUT... just like Schrödinger's cat, we shouldn't need that. Maybe there's a way that whenever the data is requested from the API (which also covers the App), we check/update any item statuses based on publish date, and then return. The flow would be:

1. Request published data from API
2. API checks if collection has `status` _and_ `published_date` fields, if it does:
3. Run a query like: `UPDATE [collection] WHERE published_date <= NOW() AND status == 'draft' SET status = 'published'`
4. Run the normal/requested query to return published data

Those are my initial thoughts! I love this idea, but it might be too much work for the gain (for now) since this can be accomplished on the client side by appending an `&& date_published > NOW()` to queries. Also, since our status mappings are completely customizable, we'd need to think through how this would work based on more than just "draft" and "published"... making it a _bit_ more complex. 😄

**Comment by jacobrienstra** [comment]
Ohhh interesting I had envisioned it purely as descriptive, not imperative. But being able to schedule publishing would absolutely be a great feature. Perhaps it could be an added feature of a status field, where you can either change the status yourself, which will then change the status_change to "now", or you can schedule a status change (to any status) with a datetime field. 

As far as chron job stuff, the use case I was thinking of was using a webhook on publish, which then triggers a rebuild of a static site. In which case. A chron job would be needed. But otherwise I think the API on request method works.

I also agree this isn't a super necessary feature, and can be sort of bootstrapped from existing things.
