### ISSUE TITLE
Swap `deselect` with `replace` when file interface is required

### ISSUE THREAD

**Issue by GMTA** [directus/app#2422]
A field of type "File" set to Required still gives you the option to delete the file when editing the item, breaking the relationship constraint and resulting in "This item is not available".

**Comment by rijkvanzanten** [comment]
We've since added an option to hide the `delete` option from the file interface. Preventing the file from being deselected–even when it's required–would prevent the user from selecting a new image.

I think the `allowDelete` option for the `file` interface solves this issue. Please let me know if you disagree @GMTA and we can reopen and continue the conversation 🙂

**Comment by GMTA** [comment]
Hi @rijkvanzanten, thanks!

Just to make sure I understand it correctly; it's now possible to hide the `delete` action which simultaneously prevents replacing an existing image?

Wouldn't it make more sense to have the following defaults?

* Required fields: provide `replace` action, do not allow the file to disappear
* Optional fields: provide `replace` and `delete` actions

**Comment by rijkvanzanten** [comment]
Currently there's a difference between `delete` and `deselect`. We added an option to hide the `delete` option, which prevents users from completely deleting the related file.

I do like the idea of swapping out `deselect` with `replace` when the `file` is required

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
