### ISSUE TITLE
datetime interface : input content is erased when I finish my typing.

### ISSUE THREAD

**Issue by lhapaipai** [directus/app#2537]
Hi there,
thank you for your work !
After upgrading from 8.4 to 8.5.3, I have a problem with the datetime interface.
```json
{"format":"dmy","localized":false}
```
step to reproduce :
when I create a new item from a collection with date interface.
on the end when entering my date, the content of the control is erased.
![datetime](https://user-images.githubusercontent.com/1088155/73791170-17ee7900-47a2-11ea-825e-2b033cdd66f3.gif)

no error reported in console and in directus/api logs.

**Comment by rijkvanzanten** [comment]
This is caused by a dependency change. Directus relies on `date-fns` > 2.x, but the `v-timeago` library tries to import `date-fns` `1.x`.

Removing the `v-timeago` dependency in favor of a Directus internal utility function based on `date-fns` `2.x` is already on the planning, so we'll move that up in priority as it will allows us to resolve this too.
