### ISSUE TITLE
Enhance navigation among records, both existing or newly created

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2670]
# Feature Request
It would be nice to be able:
- to cycle through existing records in a Collection: left and right arrows
- to open a new record as soon as the user has validated a new record

## What problem does this feature solve?
Overall, the navigation interface seems a bit cumbersome, mostly when compared to proprietary DBMSes: FileMaker, 4D, Access, etc.

## How do you think this should be implemented?
- left and right arrow on existing record
- ability to preselect a "Roll through new records" option as a checkbox or a menu option

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by asitemade4u** [comment]
Just that as soon you are finished adding a record in a collection, you 
are shown a new blank record instead of going back to the list.

Much faster to input data that way.

**Comment by rijkvanzanten** [comment]
Ah, we have that under save-and-add-new when you click the triple dots next to the save button instead of the save button. We can consider adding an option to make that the default system wide though (@2674

**Comment by benhaynes** [comment]
I do like the idea of previous and next arrows on the item detail page, but would that be confusing because of differences in sort order and filtering?

I don't think we'd want to make changing the save action a global setting, since that would change how it works for users without them knowing (if an admin changes it at a random time). I'd be open to discussing it at the user level though.

Another direction to go would be to embrace keyboard shortcuts more seriously. So Meta-S saves and stats, but Meta-Shift-S saves and returns, etc. If we had combinations for each option, users would have the speed they need.

**Comment by rijkvanzanten** [comment]
To be fair, cmd+s already performs save and stay right now 🙂

**Comment by benhaynes** [comment]
I also think the "more" option of the save action button needs to be more prominent. It's often overlooked.

**Comment by rijkvanzanten** [comment]
We should also render the shortcut in the option dropdown. Otherwise there's no way of knowing they exist. Just like this:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/9141017/77233577-da418600-6b7e-11ea-91df-becf409aa38e.png">
