### ISSUE TITLE
How do I display images in a Files field?

### ISSUE THREAD

**Issue by asitemade4u** [directus/app#2674]
1. I have created a "Gallery" field as a `Files` field.
1. I display the `tags` and `description` fields of the image file by adding them in the **Visible Columns** field of the `Files` field **Options** page
1. But how do I add the thumbnail of the image on each line? I have tried many keywords, but in vain: thumb, thumbnail, image, file-content, picture, etc.

Frankly, the documentation is somewhat thin on the subject. A list of acceptable keywords would be greatly appreciated.

**Comment by asitemade4u** [comment]
/Images/ should preferably be called /Gallery/, which is a very common 
term both in CMSes (WP) and in Headless CMSes (Strapi, Cockpit).

**Comment by benhaynes** [comment]
I agree with all of this, but wonder about the `images` vs `gallery` naming. I don't know why, but "gallery seems a bit more opinionated about how you'll use them. Is it always a gallery if you want to select multiple images?

I know that seems a bit pedantic, but we definitely want to keep Directus close to *data-first*, not limited to *content-first*... and "Gallery" seems more specific to how you use it in your own presentation layer. In Directus, we might show these in a tabular view... while a gallery is seems more like a slideshow or card-grid.

Also, maybe this won't be an issue in v9+ since we're splitting interfaces from displays!

All IMHO... down to discuss.

**Comment by rijkvanzanten** [comment]
> Also, maybe this won't be an issue in v9+ since we're splitting interfaces from displays!

That doesn't matter in this case though, the question, is a set of multiple units of image `images` or `gallery`, which I think should be the former.

**Comment by spee** [comment]
I would love an `images` field, which would also be selectable for the Image Preview in cards view.

**Comment by rijkvanzanten** [comment]
@asitemade4u Why did you close this? This hasn't been resolved yet
