### ISSUE TITLE
Improve wording regarding Translations (Interface vs Field title)

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2718]
As discussed with @rijkvanzanten on Slack, the wording related to Translations is currently confusing.

![image](https://user-images.githubusercontent.com/3807458/78512324-e6932900-77a3-11ea-9a05-f51c84374929.png)
This is the Translation Interface, it should be renamed as "Content Translation" interface.

![image](https://user-images.githubusercontent.com/3807458/78512332-ee52cd80-77a3-11ea-8726-0dd1cd71ffdd.png)
This is for the translation of the Field, it's completely different from content translation, but it's also very confusing the first time one configures translations. It should be renamed as "Field Title Translation" instead.

@benhaynes What do you think about the proposed wording?

It seems rather trivial to do, because it only changes labels, not behaviours. Docs should also be updated. I wonder if that shouldn't be integrated with the upcoming v9.

**Comment by benhaynes** [comment]
I agree that the naming should be changed to separate these two, but while these changes seem easy, they can sometimes be more difficult since they can lead to breaking changes. But here is what I would recommend:

* Interface: `translations` or `multilingual` or `multilingual_form` or `multilingual_fields` or `multilingual_group`
* Field Translations: `field_translations` or `field_name_translations`

Also, an explanation note for field translations would help a lot.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
