### ISSUE TITLE
Translation items are not deleted when parent is deleted

### ISSUE THREAD

**Issue by fribeau** [directus/app#2762]
I have followed [this tutorial](https://docs.directus.io/guides/relationships.html#translations) in the documentation to setup the translations.
If I delete an `article` in the app, the correspondent translations are not removed from the database.

## Technical details
- Device: Desktop Firefox 75.0
- OS: Ubuntu 18.04.4 LTS
- Web Server: Apache/2.4.29 (Ubuntu)
- PHP Version: 7.2.24-0ubuntu0.18.04.4
- Database: mysql Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using EditLine wrapper
- Directus Release Version: 8.6.2
- Install Method: cloned master branch

**Comment by rijkvanzanten** [comment]
This is expected behavior. Directus doesn't delete any related items by default, as they can be related to other items themselves, which can get messy really fast. If you have any solid ideas on how this should ideally work, feel free to voice your thoughts on the open feature request for this: https://github.com/directus/api/issues/384
