### ISSUE TITLE
Deleted Collection Record with Unique value enabled does not allow another record with same value

### ISSUE THREAD

**Issue by tshah3016** [directus/app#2792]
Hi

I am on the latest version of Directus and have done the dev setup using a docker image, I have created a collection with a column that is marked as unique. I created a new record for the collection in the status draft and then deleted the record using the trash bin icon. After deleting it I tried to create a new record and gave the same value as the last time. When trying to save I get an error saying that another record exists with the value. 

When I checked MySql I see that the older record is not deleted just the status is marked as deleted. I did not find any UX interface to delete these soft deleted records. 

Regards
Tejas

**Comment by rijkvanzanten** [comment]
Hi @tshah3016 

When your collection has a status field with a status that's marked as soft-delete, the app will soft-delete instead of delete the item, which effectively means update the status and hide the item in the app / api. The only way to hard delete these soft deleted items (in v8) is in the database directly.

(In v9+, we're surfacing a dedicated "hard delete" vs "soft delete" button for admins, so there's a way in the UI to manage soft deleted items, see https://github.com/directus/app-next/issues/344)
