### ISSUE TITLE
Non Admin User - Module Bar broken and does not render

### ISSUE THREAD

**Issue by KennyMl** [directus/app#2924]
Directus Cloud Plan.
Login with non admin user (access to only one user collection)
Unable to Load side module bar.

Tried different themes,
Tried different browsers (Chrome, Chromium and firefox on linux),
Tried a few different permissions,
Tried adding custom module.

This is blocking us from using (as we cannot access files* or log a user out etc)

*For now, as a workaround, I manually went to files URL and created a bookmark.

Issue in console (generic vue error I assume):

vue.runtime.esm.js:1888 TypeError: Cannot read property 'startsWith' of undefined
    at module-bar.vue?ac89:1
    at a.Nt [as _l] (vue.runtime.esm.js:2630)
    at a.Sr (module-bar.vue?ac89:1)
    at vue-composition-api.module.js:604
    at te (vue-composition-api.module.js:565)
    at a.t.render (vue-composition-api.module.js:604)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.run (vue.runtime.esm.js:4554)

**Comment by benhaynes** [comment]
Hey @KennyMl — we try to keep GitHub for bugs and feature requests only. For Cloud issues, please use our chat service: https://directus.io/

As for your issue, the most likely cause is that the new role's permissions are too limited. Within permissions, you can expand to see "system collections", and those have intentional defaults that are required to run the App properly. I would start there by checking that you did not change/limit those system settings.

**Comment by KennyMl** [comment]
Thanks Ben - I raised the bug as I thought it be better than spamming the chat :) (i.e. let it be triaged separately).  

It didn't seem to be a permission issue (I seen these were already set to defaults for system).

I may have broken module config at some point when testing.  I will double check this later in case there is a bug, but lets call it a user issue for the time being.
