### ISSUE TITLE
Add proper error handling

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#45]
Most data fetching only uses `console.error` right now. We need to show the user a notification that something went wrong.

Use the notifications as added in #42

**Comment by honzabilek4** [comment]
I'm working on this one.

**Comment by rijkvanzanten** [comment]
It would be nice if there is a single error global handler that can be extended when needed in the future. I'm playing with the idea of adding something like [Sentry](https://sentry.io/welcome/) or something similar in the future, so we can really get Directus ~bug free~ as bug free as humanly possible

**Comment by honzabilek4** [comment]
There's already an errorHandler function in Vue.config object, which should serve exactly this purpose. There's no much being said in the docs, but I did a quick research.
It gets called whenever an uncaught error appears in a component. You can also override this handler in a component if needed. This method goes along well with Sentry or similar, since they're using exactly the same approach, meaning we can easily swap it once decided.
