### ISSUE TITLE
Demo in parts not usable

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#558]
There are a lot of errors and missing css files in the Directus 7 demo on https://next.directus.app. Same on my local installation (MacOS, NGINX, MySQL) using the database scheme here: https://sql.directus.app/demo.sql.

The main problem is that I can't save new items of an collection and some fields or extensions doesn't work. 

**My steps:**

After login I click on a non-single collection e.g. Concessions. A lot of css files from api extensions are missing (404 error):
load-extension.js:41 GET ..../extensions/core/listings/tabular/listing.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/primary-key/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/text-input/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/numeric/readonly.css 404 ()
load-extension.js:41 GET ..../extensions/core/interfaces/sort/readonly.css 404 ()

I click on the first item of the collection and get an error: 
"There was a problem loading the category extension." 

The Category-Field is just a text input - not sure if this ok or should be something else.

I go back to the collection and add a new item. Same error as before. 'Save' button is disabled.
In my local installation I get Vue warns like this: 

[Vue warn]: Error in created hook: "Error: Invalid string value: undefined, Argument Name: collection", found in
---> <InterfaceManyToOne>
       <VInterfaceExtension> at src/components/extensions/interface/interface.vue
         <VField> at src/components/edit-form/field.vue
           <EditForm> at src/components/edit-form/edit-form.vue
             <Edit> at src/routes/edit.vue
               <Directus> at src/app.vue
                 <Root>

Save Button stays disabled even if I fill out an input field. Or all input fields. I can't save the item. Instead for every field I get an error: 

TypeError: Cannot read property '[name of the field]' of null.

Then I go to the settings and add a new collection called 'Test'. First I get this error: 'There was a problem loading the extension.' I can add Fields, but when I click on save I get: 

We're having some trouble processing your request.. Please try again by refreshing this page. If the problem persists, please contact your system administrator.' 

And in the console I get: '205 - message: "Collection "test" is not being managed by Directus"'

When I go back to the collections I can see the new collection in the list. But I can't add new items. Same as above.

Then I try to edit my user profile. The Demo site is offline at the moment, so I can just report errors for my local installation. Here I got certain Vue warns e.g. 

'Invalid prop: type check failed for prop "id". Expected String, got Null.' found in <VInterfaceExtension> at src/components/extensions/interface/interface.vue

Or: Invalid prop: type check failed for prop "modelValue". Expected String, got Number. Found in <VRadio> at src/components/form-inputs/radio.vue. 

The last one is caused by the Status field and might be caused by vue expecting a value like 'published', 'under review' as a string, but in the database scheme the status is an integer.

This are the errors that I found. Hope it helps :-)

Thanks a lot for your awesome work!

**Comment by rijkvanzanten** [comment]
Thanks @Zielgestalt!

**Missing CSS Files**  
Each interface is split up in an interface.js file and an interface.css file. However, extensions without a <style> tag don't have a interface.css file generated, causing the 404 in the browser.

**Problem loading [X] extension error / rendering text-input**  
We haven't finished all extensions yet, so certain interfaces aren't able to load. The app falls back to the text-input extension. This is expected behavior for now.

🐛 **205 - message: "Collection "test" is not being managed by Directus**  
When creating a new collection, it should automatically be managed by Directus. Not sure why it didn't set that. I know we just yesterday pushed a commit to the API that changes some things about this managed flag, so this might be related https://github.com/directus/api/issues/240

🐛 **'Invalid prop: type check failed for prop "id". Expected String, got Null.' found in at src/components/extensions/interface/interface.vue**  
The app expects each field to have an `interface` setup. The API is able to return fields without an interface setup, in the case the field was created in the DB directly and isn't "managed" by Directus. The app should automatically fallback if there isn't an `interface` id passed

🐛 **Or: Invalid prop: type check failed for prop "modelValue". Expected String, got Number. Found in at src/components/form-inputs/radio.vue.**

> The last one is caused by the Status field and might be caused by vue expecting a value like 'published', 'under review' as a string, but in the database scheme the status is an integer.

You're right! However, the status value can be both as it's user configured. Therefore, the interface should accept and work with both String and Numeric values.

**Comment by rijkvanzanten** [comment]
I went over all of these and (except for the first two), they're all solved.
