### ISSUE TITLE
[Discussion] Caching / Data fetching

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#611]
Right now, Directus fetches everything for every page fresh in order to make sure that the data is the same as in the database. While the API is pretty fast, we're still re-fetching data that most likely didn't change since the last page, like collections and fields, or permissions.

In order to solve this, we should implement some sort of caching. This is a hard subject to tackle correctly, as there are a lot of uses and use cases where you could want different caching strategies.

I think caching should be a setting for the user, and might even be set on a collection level.

**Comment by benhaynes** [comment]
I agree with it being a setting on the collection-level, perhaps with a global default. I don't think it needs to be a user setting though. Here are a few ideas for schema and collection-level data caching/fetching:

### Schema Fetch Interval
For schema data/changes, we could base this on if the API is in `production` or `development` mode... or create some sort of `schema_lock` flag.

### Collection: Data Fetch Interval
Each collection's data can be async fetched based on a `directus_collections.fetch_interval` INT value. Since we have a CRON job that already runs every 10s, we can fetch data at any 10s multiple. Some examples:

* `0` – This data does not change, or changes _very_rarely. We can fetch it once on page load (or when it's needed) and then we can cache it client-side. This saves `0`, but  we could use an alternate name for this in the interface UI, like: `Fixed`, `Static`, `Once`, `Locked`, `Load`, etc
* `1` – This is live data (the fastest we can/will/should fetch data (until websockets). It would be fetched on load and then again every 10 seconds.
* `6` – This is normal data. Fetched on load and then again every minute (6 * 10s)

### Collection: Data Pre-Load
Another possible option would be a `directus_collections.prefetch` BOOLEAN to force the App to fetch a collection's entire dataset on App load. We could disable this feature when the data set is >X. When used in combination with the Fetch Interval, admins would have a lot of control over App performance optimizations.

### Polling Activity Check
We could also load data once and then poll `directus_activity` to see if any changes have been made since the last fetch. In that way, we intelligently load new data only when needed. My main issue with this is that it doesn't allow for data to be entered directly into the database (skips activity). For that reason, if we chose to implement this feature it would have to be optional.

### Fetch vs Cache
While smart-fetching in the App is fastest, we could have similar caching layer in the API (or maybe we already have this?). API is good for projects with many users since there are fewer DB hits.

**Comment by rijkvanzanten** [comment]
It's such a shift in paradigm that it's future dreams for now

**Comment by adamjgrant** [comment]
As a user, it would be great to have something that is MVP-ish for now. 

In my case, I have a "single" type collection where I just store general site settings like the little copyright in the footer, a system-wide banner message that users can dismiss...just stuff that I want to update easily but isn't going to change very frequently at all.

So having some little setting for a collection to say "cache for x seconds", defaulting to 0, would be super useful.

cc: @rijkvanzanten @benhaynes

**Comment by benhaynes** [comment]
I agree @adamjgrant — but we have open-source resources so we need to prioritize bugs and stability first. We'll get to this, but unless a company wants to "sponsor" it, it unfortunately needs to wait a bit.

**Comment by rijkvanzanten** [comment]
Also, I think this specific usecase might be covered by the API caching that already exists :)

(Although we should really have it invalidate on update instead of just time)

**Comment by adamjgrant** [comment]
@benhaynes Totally understand! Just wanted to add my plus 1 to this for when the time comes to revisit this. Caching is tricky territory anyway. 

Thanks

**Comment by srjrol** [comment]
@benhaynes @rijkvanzanten If we could start by limiting the fetched rows for the table collection views to those that are selected under info this would help me a great deal!  It appears a fresh request is made after column selections are changed but the same data (all) is retrieved.  I see it is currently expected behavior but for me, it is a major problem resulting in huge JSON files and high load times.

**Comment by benhaynes** [comment]
Hey @srjrol — it seems like you have a lot of deeply nested relational data. We will likely be addressing this in the App refactor starting in a few weeks (will probably have each field request the data depth it needs instead of doing this at the collection level).

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
