### ISSUE TITLE
Allow recursively relating an item to itself

### ISSUE THREAD

**Issue by benhaynes** [directus/app#748]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Allow recursively relating an item to itself
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
This is not a critical fix because there is no good reason to recursively relate content to itself – but it's worth documenting. If you have an item and it's also included (related) to itself in a many-to-many UI – changes to the parent aren't respected to due being overwritten by the child (related) item.

**Comment by benhaynes** [comment]
@rijkvanzanten is this an issue now that we use one _store_ in vue?

**Comment by rijkvanzanten** [comment]
This is a very interesting situation indeed. I haven't created any exceptions or overrides for this to work "properly".

The main edits are in the root level, the inner related many to many staged edits are in a nested object.

```
// edits
id: 1,
title: "The New Title",
m2mField: [
  {
    id: 1,
    title: "The inner-related title"
  }
]
```

I haven't tested this, but I'm assuming that the API will error 500 out because we're trying to update the same field to two different values.

We've been thinking about storing all the record values themselves in the store as well in https://github.com/directus/app/issues/611. That would theoretically solve this issue as well, seeing that the application will pull the record info from the same place for both.

The alternative solution would be for the m2m / o2m interface to take the store edits into account when displaying the modal edit form, but that feels more like a fix than a solution.
