### ISSUE TITLE
Layout: Split View

### ISSUE THREAD

**Issue by benhaynes** [directus/app#783]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Vertical Split Listing View
### :+1: = 1
*Created 7 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (7 months ago)
Click an item, it opens in a right pane.

https://cdn.dribbble.com/users/13503/screenshots/3857446/shot.png

**Comment by benhaynes** [comment]
I have a design for this...

**Comment by rijkvanzanten** [comment]
Care to share?

**Comment by benhaynes** [comment]
![directus 7 split view](https://user-images.githubusercontent.com/522079/45255380-a499cb00-b353-11e8-897f-b3e792ec49e6.png)

### Details

* Clicking an item opens the item in a right pane.
* The page's info sidebar still opens _over_ this pane.
* Selecting multiple item checkboxes uses the batch edit pane.
* Clicking the pane's left-arrow closes the item pane.
* Clicking the pane's Save button saves the item(s) and closes the pane.
* Pane is resizable (drag-and-drop); hitzone should be a larger transparent element.
* App Header
    * Suppress Batch Edit button on multiple select
    * Can still use this Delete button (or we can move to pane header)

**Comment by Nitwel** [comment]
Hey, so at the moment, it is planned that this will be a layout.
I had some thoughts about that and Im not sure if this would be the right way to implement.

Making this not a layout but implementing it in the core of directus would have huge benefits.
You could allow users to open the "split view" for every layout they installed rather than for a single layout (list view) which has been build into the "split view". 

It also could be implemented as an page-extension but I never have seen how directus implements them before and Im not that sure if a page-extension could allow such feature. ( @rijkvanzanten is this possible? )

I hope you get my point why this could also be a core feature / page-extension rather than just a single layout-extension.

**Comment by rijkvanzanten** [comment]
That's a very good point @Nitwel, that would allow the split to work with layouts like the map as well. Thoughts @benhaynes?

**Comment by Nitwel** [comment]
And I also started trying, doing it the "page" way, and many questions and issues start to come up, like:

1. When you have this "page-extension" selected, how do you select which table you want to open?
-> implementing an additional select for tables would be realy *stupid* cause then there would be 2 ways to select a table.
-> having the posibility to select the extension aand the table you want to use would be very confusing

2. You have to mostly just copy the code of the items.vue/item.vue endpoint and some other files to the extension, which duplicates code and makes it hard to apply redesigns or changes to the system.

3. Having such splitView extension beneath all other tables is somewhat a realy bad place for intuitive usage.
-> Heres how I would implement it:
![split view](https://user-images.githubusercontent.com/22577866/51427162-b7bb8200-1bf4-11e9-8425-96d397f0ddb1.png)

**Comment by benhaynes** [comment]
I like the idea of making a "detail sidebar component" for the v7.1 UX since we'll have modular info sidebar components. Then we can use it for any layout. Quick mock:

![directus 8 browse info sidebar](https://user-images.githubusercontent.com/522079/51429531-47553680-1bdd-11e9-9cce-14f264201209.png)

**Comment by Nitwel** [comment]
Looking awesome 👍

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
