### ISSUE TITLE
Nothing is displayed

### ISSUE THREAD

**Issue by bpiwowar** [directus/app#849]
## Describe the Bug

After logging, an almost empty page is displayed:

```extension
No Extensions Found

Make sure you have the system extensions installed.
```

All the XHR requests seem OK (status 200). Maybe I miss something in the configuration, but not clear what (could be a documentation issue).

## Steps to Reproduce

1. Fresh installation with local API server

## Screenshots

<img width="261" alt="image" src="https://user-images.githubusercontent.com/423314/45925014-7d272e80-bf0d-11e8-83b2-b07452223ea9.png">

## Technical Details

- Device: Desktop (MacBook Pro)
- OS: MacOS 10.13.6 with MAMP (PHP 7.1.12)
- Browser: Firefox 63.0b8
- Directus App: From github branch "build" (v7.0.0-rc.3)
- Directus API: master branch (a0baf473f2450d5148320a468db4bacd2221fd7f)

**Comment by benhaynes** [comment]
This won't be an issue when we have the `build` version released (hopefully later today) since that will have the Directus Extensions built-in. Also, it is a Docs issue in that the links of the different pages are mostly broken (while we settle on header names).

This should be what you're looking for:

https://docs.directus.io/api/contributor-guide/install-dev.html#_3-install-the-npm-dependencies-of-and-build-the-extensions
