### ISSUE TITLE
Unable to create a one to many relationship

### ISSUE THREAD

**Issue by chrisgame** [directus/app#851]
When I try to create a simple one to many relationship between two collections I get a server error when attempting to view the collection with the relationship.

## Steps to Reproduce
1. Create a collection called "children"
2. Create a collection called "parents"
3. Add a one to many relationship to the parents collection, joining on id 
4. Click save 
5. Click on the parents collection
6. See error

## Expected Behavior
Not sure if I have set the relationship up correctly but I wasn't expecting an error to occur when viewing the collection.

## Screen Capture
![unable to save a relationship](https://user-images.githubusercontent.com/766429/46077050-68ee6600-c187-11e8-98d0-18f980ff118b.gif)

## Technical Details
- Device: MacBookPro
- OS: MacOS 10.13.6
- Browser: Chrome 69.0.3497.100
- Directus App: 11b722bc60df520cba5e2d67ce5e82d62ac1acf0
- Directus API: 7e839a8bfb8e29e01bf614935521320fb28d58d4

**Comment by chrisgame** [comment]
Also reproducible on https://next.directus.app/login
The collections I created are still on there `chris_test_parents` and `chris_test_children`

**Comment by rijkvanzanten** [comment]
Hey @chrisgame! This is indeed caused by a wrong setup of the relationship. The parent side controls what value to store in a child's field, so this:

![image](https://user-images.githubusercontent.com/9141017/46224817-5ca00f80-c325-11e8-9bfb-511e4564f782.png)

means that the parent will try saving it's ID into the `id` field of the child item, which causes the error.

A setup like this

![image](https://user-images.githubusercontent.com/9141017/46224927-abe64000-c325-11e8-8f77-6be9e23a09fd.png)

works as expected 🙂

**Comment by benhaynes** [comment]
We just discussed this and decided that to make this a bit more fool-proof we won't include the primary-key as an option within the related collection's fields. We'll also outline relations setup more clearly in the docs.

Thanks @chrisgame – this is one of the clearest and best formatted issues I've seen posted here!

**Comment by benhaynes** [comment]
I've added some screenshots, helper text, and tips to the (upcoming) Docs update. Hopefully this helps! Let me know if the terminology should be tweaked.
