### ISSUE TITLE
Settings>Fields: Many type check errors

### ISSUE THREAD

**Issue by benhaynes** [directus/app#900]
Every time I open the Field Modal, I am getting 15-20 errors:

![screen shot 2018-09-30 at 11 49 24 am](https://user-images.githubusercontent.com/522079/46259400-e4615780-c4a6-11e8-885d-8110a2b522de.png)

**Comment by mclintprojects** [comment]
Hello @benhaynes. I am trying to fix this issue next but when I try to login to the demo API I get this error `Status code: 500 | {"error":{"code":null,"message":"Statement could not be executed (42S22 - 1054 - Unknown column 'DF.hidden_input' in 'field list')"}}`

**Comment by benhaynes** [comment]
Ahh, yeah there were a few schema changes a few days ago. This ticket has the database columns that were renamed:

https://github.com/directus/api/issues/445

**Comment by mclintprojects** [comment]
Hello, @benhaynes. I pulled the latest changes from upstream master and this issue still isn't fixed so I'm still unable to login locally. It seems that there's a directus field in the demo API that is still `hidden_input` instead of `hidden_detail`. Are you able to login to the app with the demo API locally? If yes, please let me know how you managed to do it.

**Comment by benhaynes** [comment]
Ahh, you are right... I am getting that error too.

@rijkvanzanten if I updated demo.sql with these new field names (`hidden_browse` and `hidden_detail`) shouldn't it have pulled that in and be working?

**Comment by rijkvanzanten** [comment]
I don't see the same issue on `next.directus.app`. Are you sure you're using the latest demo api (https://next.demo-api.directus.app)?

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/commit/db10650fa38a3d579abc606f7e1192d203cb0765
