### ISSUE TITLE
Settings: Can't Change Options Toggle

### ISSUE THREAD

**Issue by benhaynes** [directus/app#934]
When I try to change the `tags` interface options (eg: turn `lowercase` off):

1. I click the `lowercase` toggle (it turns off)
1. I get some type errors (see below)
1. I hit save
1. I open up the modal and it didn't save

```
vue.runtime.esm.js?2b0e:587 [Vue warn]: Invalid prop: type check failed for prop "value". Expected Boolean, got Number.

found in

---> <VToggle> at src/components/form-inputs/toggle.vue
       <VModal> at src/components/modals/modal.vue
         <VFieldSetup> at src/components/field-setup.vue
           <SettingsFields> at src/routes/settings/fields.vue
             <Directus> at src/app.vue
               <Root>
```

**Comment by andreasvirkus** [comment]
Hi there. I've just discovered your app through the hacktoberfest label and (since I'm looking for a bit more meaningful projects to contribute to) was wondering if it'd be ok to tackle this as my first (hopefully of many) contribution to this repo? 🐰 

I looked through the setting up locally guide and this issue can be tackled without the API (or if so, targeting the demo API), right? Or does the toggle belong under an extension (sorry, not sure yet what constitutes an extension)?

Best,
andreas

**Comment by benhaynes** [comment]
Hey @andreasvirkus – we'd absolutely love the help! 

All extension code _does_ live in the API repo ([explanation](https://docs.directus.io/extensions/architecture.html)) but system components like toggles still live in the App repo. @rijkvanzanten would know best what's needed, but it's possible that this can be resolved by [installing just the App locally](https://docs.directus.io/app/contributor-guide/install-dev.html) and then using the [public demo API](https://demo-api.directus.app/_/).

Let us know if you run into any issues... we're happy to help, fix, or clarify the docs to make things clearer!
