### ISSUE TITLE
Interface: Divider>Options – Divider Text

### ISSUE THREAD

**Issue by benhaynes** [directus/app#939]
When you try to delete the default text in `divider-text` or `divider-description` it resets the default text when the value is empty. If you delete the text, it should stay empty. 

Also, it's trimming whitespace off the end of the value. (If you have `testing 1` and delete `1`... it also deletes the space).

Both of these issues make it very easy to make a mistake when entering values.

![screen shot 2018-10-08 at 2 59 27 pm](https://user-images.githubusercontent.com/522079/46628232-e496ce00-cb0a-11e8-9227-0002345c3dd7.png)

**Comment by rijkvanzanten** [comment]
The reason that the interface is reset with the original value is because it falls back to it:

https://github.com/directus/app/blob/5d5656d338fe2603daf4f23fe710a7d9f2c9e439/src/components/field-setup.vue#L239

The backspace-issue is caused by the `trim` option:

https://github.com/directus/api/blob/3bd595cb308c024ddad18c8d7c7a2974f422e55b/extensions/core/interfaces/text-input/input.vue#L25-L27

Trimming works just fine when writing, but when back-spacing, it feels very unnatural. This trimming should only happen when the value's length increases, not decreases, so it only trims on adding characters.

**Comment by benhaynes** [comment]
In my opinion the trim should only happen on Save, if that's possible

**Comment by rijkvanzanten** [comment]
It's not @benhaynes, interfaces can send up values to the parent, but are completely agnostic as to what happens to that value.

**Comment by benhaynes** [comment]
Gotcha. Then checking if you're typing forward or "backwards" seems like the next best solution.
