### ISSUE TITLE
WYSIWYG Button Order

### ISSUE THREAD

**Issue by benhaynes** [directus/app#944]
The button is being saved in a different order (alphabetically), which then makes the editor very confusing. Buttons should be saved in the order of the options...

The options display in this order:

![screen shot 2018-10-08 at 4 37 20 pm](https://user-images.githubusercontent.com/522079/46632395-7f49d980-cb18-11e8-90b8-6edda79a5aa2.png)

But this saves in the DB as:

```
{"buttons":["anchor","bold","h2","h3","italic","orderedlist","quote","underline","unorderedlist"]}
```

Which then displays in the App as:

![screen shot 2018-10-08 at 4 38 38 pm](https://user-images.githubusercontent.com/522079/46632429-a1dbf280-cb18-11e8-823f-a82780bb5d26.png)

**Comment by rijkvanzanten** [comment]
This is actually caused by the `checkboxes` interface! The WYSIWYG interface is using the checkboxes for this setting:

https://github.com/directus/api/blob/d3074d125202d39ac4dbb2055d1dfc2c1609e546/extensions/core/interfaces/wysiwyg/meta.json#L16

And is then using the value as saved in the DB directly for the toolbar.

The `checkboxes` interface is sorting the values alphabetically:

https://github.com/directus/api/blob/d3074d125202d39ac4dbb2055d1dfc2c1609e546/extensions/core/interfaces/checkboxes/input.vue#L47

**Comment by benhaynes** [comment]
Ahhh, makes sense! Fixed!

**Comment by benhaynes** [comment]
Ref: https://github.com/directus/api/commit/3bd595cb308c024ddad18c8d7c7a2974f422e55b
