### ISSUE TITLE
Creating Item Page Title

### ISSUE THREAD

**Issue by benhaynes** [directus/app#947]
The page title (as seen in browser tab) is saying "Editing XXXX" when creating an item. Page titles should say:

* Creating: `Creating Item: [collection-name]`
* Updating: `Editing Item: [collection-name]`
* Batch Updating: `Batch Editing Items: [collection-name]`

**Comment by tthompson899** [comment]
I'd like to work on this issue

**Comment by benhaynes** [comment]
Hey @tthompson899 – that sounds great, thank you! Consider it yours!

**Comment by rijkvanzanten** [comment]
@tthompson899 This is the bit of code that sets that title:

https://github.com/directus/app/blob/d14102ee12010e798ecee5d321e8feec23c322a8/src/routes/item.vue#L183-L193

As you can see, it's always returning the translation for "editing".
`this.$t` is using this translation: https://github.com/directus/app/blob/d14102ee12010e798ecee5d321e8feec23c322a8/src/lang/locales/en-US.js#L186

The fix for this would be to add a few extra conditionals in that `metaInfo` method above that returns other strings if the item is new or batch. You should be able to use `this.isNew` and `this.batch` to check for that 😄

**Comment by tthompson899** [comment]
@rijkvanzanten Good to know! I was looking in that file so I was close 😄

**Comment by tthompson899** [comment]
Ready for review.
