### ISSUE TITLE
Recommended Settings for Interfaces

### ISSUE THREAD

**Issue by benhaynes** [directus/app#952]
The status is not showing `20` as the default/recommended length. Also, can we outline all possible recommended settings and their keys here?

![screen shot 2018-10-09 at 5 22 42 pm](https://user-images.githubusercontent.com/522079/46699480-f69a6e80-cbe7-11e8-9742-599c07b5ac62.png)

**Comment by rijkvanzanten** [comment]
```
{
  "types": ["status"],
  "recommended": {
    "defaultValue": "draft",
    "length": 20
  }
}
```

This is the currently supported way in `meta.json`. This object could be extended to add support for other keys as well

**Comment by benhaynes** [comment]
Do you like `defaultValue` more than just `default`?

Does/can the App choose the SQL datatype based on the recommended length? For instance, the WYSIWYG editor still defaults to VARCHAR(255)... which clearly won't work.

Also, should I open separate tickets for these or use this ticket?

* Hidden On Browse (for sort)
* Hidden On Detail (for primary key, sort)
* Readonly (for Created On and Created By)
* Note (for status, primary key, sort, and other system fields)

**Comment by rijkvanzanten** [comment]
On `defaultValue` vs `value`, we're technically setting the `default_value` of the column, that's why. Also, I figured we might want to add something like `defaultType` or something which would make `default` and `defaultType` confusing.

> Does/can the App choose the SQL datatype based on the recommended length? For instance, the WYSIWYG editor still defaults to VARCHAR(255)... which clearly won't work.

It doesn't (yet). I don't want to set the MySQL specific type in the interface, as that would be a maintenance nightmare. How would the application decide what's best to use based on length? We need to come up with a lookup table:

| recommended length | type |
|-----------------------|-----|
| x < 50                             | CHAR |
| 50 < x < 255               | VARCHAR |
| 255 < x < ?                 | TINYTEXT |

etc


> Also, should I open separate tickets for these or use this ticket?

Nah, lets use this one.

**Comment by benhaynes** [comment]
Yeah, that's what I was thinking. The mapping will have to be SQL vendor specific, but here is what I'm thinking for MySQL:

| Recommended Length | MySQL Datatype |
|-----------------------|-------------------|
| x <= 500                         | VARCHAR            |
| 500 < x < 65,535           | TEXT                    |
| 65,535 < x                      | LONGTEXT          |

We don't need to include all of the datatypes, just enough to ensure that interfaces can work properly. with the three above we can have VARCHAR for short blurbs (text inputs), TEXT for paragraphs of plaintext (text area), and LONGTEXT for markup (WYSIWYG or code) where formatting adds many characters.

This keeps things from breaking, and then the Admin can always go in and tweak to be more memory conscious.
