### ISSUE TITLE
error when viewing a user

### ISSUE THREAD

**Issue by Nitwel** [directus/app#979]
## Describe the Bug
When opening the "edit user" view, an _error while loading the "single_file" extention_ occurs.

- Directus App: 7.0.1
- Directus API: 2.0.1

**Comment by rijkvanzanten** [comment]
@Nitwel How did you install the api?

It should install using the `file` interface on directus_users, not the (old name) `single_file`:

https://github.com/directus/api/blob/f678d826ad5768227b097167ae28b1817c59a00a/migrations/db/seeds/FieldsSeeder.php#L1191

**Comment by benhaynes** [comment]
That's odd – the `single_file` interface was renamed to `file` before release, but your instance is still looking for the old version. We'll look into the seeder to see where this reference needs to be updated. 

In the meantime, you can update any `single_file` references within `directus_fields.interface` to be `file`... that should fix it.

**Comment by Nitwel** [comment]
https://github.com/directus/api/blob/f678d826ad5768227b097167ae28b1817c59a00a/migrations/db/seeds/FieldsSeeder.php#L940

In line 940, it also says "single_file", should it be like that?

**Comment by rijkvanzanten** [comment]
It's not in the seeder for directus_users @benhaynes, that's why I asked 🙂

**Comment by rijkvanzanten** [comment]
That's the wrong term @Nitwel, but it was correctly changed to `file` for directus_users (where you're seeing the issue) sometime ago already:

https://github.com/directus/api/blob/f678d826ad5768227b097167ae28b1817c59a00a/migrations/db/seeds/FieldsSeeder.php#L1191

**Comment by benhaynes** [comment]
On the `master` branch we definitely have updated `single_file` (incorrect) to `file` (correct). So new installs with a fresh database should work.

One issue is that the API doesn't have schema update migrations working yet, so if you already have a v7 install this won't get updated in your database. We're working on that and should have it soon.

I will close this because the issue itself is complete.
