### ISSUE TITLE
security leak / improvement => admin_token 

### ISSUE THREAD

**Issue by Nitwel** [directus/app#987]
## The issue
I would recomend using a random generated Admin-token when creating a directus instance, due to understanding leaks of the value of "tokens".

When the user, whos creating an instance, does not know what a token is, the propability that he changes the token is fairly small. Also, at the moment, theres no other way than changing the token via API or direct Database Access, which results in many instances having the "admin_token" still as a default token, which is a big security leak.

## How to improve
I suggest using **only** temporary tokens, that after a day or a new request, the token changes.

**Comment by benhaynes** [comment]
Thanks @Nitwel – this is indeed an issue for new installs using CLI. No reason to include a default token since admins may forget to change/remove it. 

We've [updated the code](https://github.com/directus/api/commit/4099ba41be563de7cdc6b62d4c641299d8e76442) so that there are NO default tokens when creating an instance/user. Thanks for the ticket!

**Comment by benhaynes** [comment]
This update will be included in v7.0.2 with this Friday's release.
